//==============================================================================
// DUT Wrapper for RTL Integration
// Generated by AMBA Bus Matrix Configuration Tool
// Date: 2025-08-04 09:41:58
// Supports 9 masters and 9 slaves
//==============================================================================

module dut_wrapper #(
    parameter ADDR_WIDTH = 32,
    parameter DATA_WIDTH = 64,
    parameter ID_WIDTH   = 4,
    parameter WIDTH_SID  = (1 + ID_WIDTH)  // WIDTH_CID + WIDTH_ID where WIDTH_CID = $clog2(2) = 1
    // Note: Slave ID signals use ID_WIDTH directly to match interconnect expectations
) (
    input  logic clk,
    input  logic rst_n,
    axi4_if.slave axi_if  // VIP connects as master to this slave interface
);

    // Internal signals for all masters
    // Master 0 signals
    logic [ID_WIDTH-1:0]     m0_awid;
    logic [ADDR_WIDTH-1:0]   m0_awaddr;
    logic [7:0]              m0_awlen;
    logic [2:0]              m0_awsize;
    logic [1:0]              m0_awburst;
    logic                    m0_awlock;
    logic [3:0]              m0_awcache;
    logic [2:0]              m0_awprot;
    logic [3:0]              m0_awqos;
    logic                    m0_awvalid;
    logic                    m0_awready;
    
    logic [DATA_WIDTH-1:0]   m0_wdata;
    logic [DATA_WIDTH/8-1:0] m0_wstrb;
    logic                    m0_wlast;
    logic                    m0_wvalid;
    logic                    m0_wready;
    
    logic [ID_WIDTH-1:0]     m0_bid;
    logic [1:0]              m0_bresp;
    logic                    m0_bvalid;
    logic                    m0_bready;
    
    logic [ID_WIDTH-1:0]     m0_arid;
    logic [ADDR_WIDTH-1:0]   m0_araddr;
    logic [7:0]              m0_arlen;
    logic [2:0]              m0_arsize;
    logic [1:0]              m0_arburst;
    logic                    m0_arlock;
    logic [3:0]              m0_arcache;
    logic [2:0]              m0_arprot;
    logic [3:0]              m0_arqos;
    logic                    m0_arvalid;
    logic                    m0_arready;
    
    logic [ID_WIDTH-1:0]     m0_rid;
    logic [DATA_WIDTH-1:0]   m0_rdata;
    logic [1:0]              m0_rresp;
    logic                    m0_rlast;
    logic                    m0_rvalid;
    logic                    m0_rready;

    // Master 1 signals
    logic [ID_WIDTH-1:0]     m1_awid;
    logic [ADDR_WIDTH-1:0]   m1_awaddr;
    logic [7:0]              m1_awlen;
    logic [2:0]              m1_awsize;
    logic [1:0]              m1_awburst;
    logic                    m1_awlock;
    logic [3:0]              m1_awcache;
    logic [2:0]              m1_awprot;
    logic [3:0]              m1_awqos;
    logic                    m1_awvalid;
    logic                    m1_awready;
    
    logic [DATA_WIDTH-1:0]   m1_wdata;
    logic [DATA_WIDTH/8-1:0] m1_wstrb;
    logic                    m1_wlast;
    logic                    m1_wvalid;
    logic                    m1_wready;
    
    logic [ID_WIDTH-1:0]     m1_bid;
    logic [1:0]              m1_bresp;
    logic                    m1_bvalid;
    logic                    m1_bready;
    
    logic [ID_WIDTH-1:0]     m1_arid;
    logic [ADDR_WIDTH-1:0]   m1_araddr;
    logic [7:0]              m1_arlen;
    logic [2:0]              m1_arsize;
    logic [1:0]              m1_arburst;
    logic                    m1_arlock;
    logic [3:0]              m1_arcache;
    logic [2:0]              m1_arprot;
    logic [3:0]              m1_arqos;
    logic                    m1_arvalid;
    logic                    m1_arready;
    
    logic [ID_WIDTH-1:0]     m1_rid;
    logic [DATA_WIDTH-1:0]   m1_rdata;
    logic [1:0]              m1_rresp;
    logic                    m1_rlast;
    logic                    m1_rvalid;
    logic                    m1_rready;

    // Master 2 signals
    logic [ID_WIDTH-1:0]     m2_awid;
    logic [ADDR_WIDTH-1:0]   m2_awaddr;
    logic [7:0]              m2_awlen;
    logic [2:0]              m2_awsize;
    logic [1:0]              m2_awburst;
    logic                    m2_awlock;
    logic [3:0]              m2_awcache;
    logic [2:0]              m2_awprot;
    logic [3:0]              m2_awqos;
    logic                    m2_awvalid;
    logic                    m2_awready;
    
    logic [DATA_WIDTH-1:0]   m2_wdata;
    logic [DATA_WIDTH/8-1:0] m2_wstrb;
    logic                    m2_wlast;
    logic                    m2_wvalid;
    logic                    m2_wready;
    
    logic [ID_WIDTH-1:0]     m2_bid;
    logic [1:0]              m2_bresp;
    logic                    m2_bvalid;
    logic                    m2_bready;
    
    logic [ID_WIDTH-1:0]     m2_arid;
    logic [ADDR_WIDTH-1:0]   m2_araddr;
    logic [7:0]              m2_arlen;
    logic [2:0]              m2_arsize;
    logic [1:0]              m2_arburst;
    logic                    m2_arlock;
    logic [3:0]              m2_arcache;
    logic [2:0]              m2_arprot;
    logic [3:0]              m2_arqos;
    logic                    m2_arvalid;
    logic                    m2_arready;
    
    logic [ID_WIDTH-1:0]     m2_rid;
    logic [DATA_WIDTH-1:0]   m2_rdata;
    logic [1:0]              m2_rresp;
    logic                    m2_rlast;
    logic                    m2_rvalid;
    logic                    m2_rready;

    // Master 3 signals
    logic [ID_WIDTH-1:0]     m3_awid;
    logic [ADDR_WIDTH-1:0]   m3_awaddr;
    logic [7:0]              m3_awlen;
    logic [2:0]              m3_awsize;
    logic [1:0]              m3_awburst;
    logic                    m3_awlock;
    logic [3:0]              m3_awcache;
    logic [2:0]              m3_awprot;
    logic [3:0]              m3_awqos;
    logic                    m3_awvalid;
    logic                    m3_awready;
    
    logic [DATA_WIDTH-1:0]   m3_wdata;
    logic [DATA_WIDTH/8-1:0] m3_wstrb;
    logic                    m3_wlast;
    logic                    m3_wvalid;
    logic                    m3_wready;
    
    logic [ID_WIDTH-1:0]     m3_bid;
    logic [1:0]              m3_bresp;
    logic                    m3_bvalid;
    logic                    m3_bready;
    
    logic [ID_WIDTH-1:0]     m3_arid;
    logic [ADDR_WIDTH-1:0]   m3_araddr;
    logic [7:0]              m3_arlen;
    logic [2:0]              m3_arsize;
    logic [1:0]              m3_arburst;
    logic                    m3_arlock;
    logic [3:0]              m3_arcache;
    logic [2:0]              m3_arprot;
    logic [3:0]              m3_arqos;
    logic                    m3_arvalid;
    logic                    m3_arready;
    
    logic [ID_WIDTH-1:0]     m3_rid;
    logic [DATA_WIDTH-1:0]   m3_rdata;
    logic [1:0]              m3_rresp;
    logic                    m3_rlast;
    logic                    m3_rvalid;
    logic                    m3_rready;

    // Master 4 signals
    logic [ID_WIDTH-1:0]     m4_awid;
    logic [ADDR_WIDTH-1:0]   m4_awaddr;
    logic [7:0]              m4_awlen;
    logic [2:0]              m4_awsize;
    logic [1:0]              m4_awburst;
    logic                    m4_awlock;
    logic [3:0]              m4_awcache;
    logic [2:0]              m4_awprot;
    logic [3:0]              m4_awqos;
    logic                    m4_awvalid;
    logic                    m4_awready;
    
    logic [DATA_WIDTH-1:0]   m4_wdata;
    logic [DATA_WIDTH/8-1:0] m4_wstrb;
    logic                    m4_wlast;
    logic                    m4_wvalid;
    logic                    m4_wready;
    
    logic [ID_WIDTH-1:0]     m4_bid;
    logic [1:0]              m4_bresp;
    logic                    m4_bvalid;
    logic                    m4_bready;
    
    logic [ID_WIDTH-1:0]     m4_arid;
    logic [ADDR_WIDTH-1:0]   m4_araddr;
    logic [7:0]              m4_arlen;
    logic [2:0]              m4_arsize;
    logic [1:0]              m4_arburst;
    logic                    m4_arlock;
    logic [3:0]              m4_arcache;
    logic [2:0]              m4_arprot;
    logic [3:0]              m4_arqos;
    logic                    m4_arvalid;
    logic                    m4_arready;
    
    logic [ID_WIDTH-1:0]     m4_rid;
    logic [DATA_WIDTH-1:0]   m4_rdata;
    logic [1:0]              m4_rresp;
    logic                    m4_rlast;
    logic                    m4_rvalid;
    logic                    m4_rready;

    // Master 5 signals
    logic [ID_WIDTH-1:0]     m5_awid;
    logic [ADDR_WIDTH-1:0]   m5_awaddr;
    logic [7:0]              m5_awlen;
    logic [2:0]              m5_awsize;
    logic [1:0]              m5_awburst;
    logic                    m5_awlock;
    logic [3:0]              m5_awcache;
    logic [2:0]              m5_awprot;
    logic [3:0]              m5_awqos;
    logic                    m5_awvalid;
    logic                    m5_awready;
    
    logic [DATA_WIDTH-1:0]   m5_wdata;
    logic [DATA_WIDTH/8-1:0] m5_wstrb;
    logic                    m5_wlast;
    logic                    m5_wvalid;
    logic                    m5_wready;
    
    logic [ID_WIDTH-1:0]     m5_bid;
    logic [1:0]              m5_bresp;
    logic                    m5_bvalid;
    logic                    m5_bready;
    
    logic [ID_WIDTH-1:0]     m5_arid;
    logic [ADDR_WIDTH-1:0]   m5_araddr;
    logic [7:0]              m5_arlen;
    logic [2:0]              m5_arsize;
    logic [1:0]              m5_arburst;
    logic                    m5_arlock;
    logic [3:0]              m5_arcache;
    logic [2:0]              m5_arprot;
    logic [3:0]              m5_arqos;
    logic                    m5_arvalid;
    logic                    m5_arready;
    
    logic [ID_WIDTH-1:0]     m5_rid;
    logic [DATA_WIDTH-1:0]   m5_rdata;
    logic [1:0]              m5_rresp;
    logic                    m5_rlast;
    logic                    m5_rvalid;
    logic                    m5_rready;

    // Master 6 signals
    logic [ID_WIDTH-1:0]     m6_awid;
    logic [ADDR_WIDTH-1:0]   m6_awaddr;
    logic [7:0]              m6_awlen;
    logic [2:0]              m6_awsize;
    logic [1:0]              m6_awburst;
    logic                    m6_awlock;
    logic [3:0]              m6_awcache;
    logic [2:0]              m6_awprot;
    logic [3:0]              m6_awqos;
    logic                    m6_awvalid;
    logic                    m6_awready;
    
    logic [DATA_WIDTH-1:0]   m6_wdata;
    logic [DATA_WIDTH/8-1:0] m6_wstrb;
    logic                    m6_wlast;
    logic                    m6_wvalid;
    logic                    m6_wready;
    
    logic [ID_WIDTH-1:0]     m6_bid;
    logic [1:0]              m6_bresp;
    logic                    m6_bvalid;
    logic                    m6_bready;
    
    logic [ID_WIDTH-1:0]     m6_arid;
    logic [ADDR_WIDTH-1:0]   m6_araddr;
    logic [7:0]              m6_arlen;
    logic [2:0]              m6_arsize;
    logic [1:0]              m6_arburst;
    logic                    m6_arlock;
    logic [3:0]              m6_arcache;
    logic [2:0]              m6_arprot;
    logic [3:0]              m6_arqos;
    logic                    m6_arvalid;
    logic                    m6_arready;
    
    logic [ID_WIDTH-1:0]     m6_rid;
    logic [DATA_WIDTH-1:0]   m6_rdata;
    logic [1:0]              m6_rresp;
    logic                    m6_rlast;
    logic                    m6_rvalid;
    logic                    m6_rready;

    // Master 7 signals
    logic [ID_WIDTH-1:0]     m7_awid;
    logic [ADDR_WIDTH-1:0]   m7_awaddr;
    logic [7:0]              m7_awlen;
    logic [2:0]              m7_awsize;
    logic [1:0]              m7_awburst;
    logic                    m7_awlock;
    logic [3:0]              m7_awcache;
    logic [2:0]              m7_awprot;
    logic [3:0]              m7_awqos;
    logic                    m7_awvalid;
    logic                    m7_awready;
    
    logic [DATA_WIDTH-1:0]   m7_wdata;
    logic [DATA_WIDTH/8-1:0] m7_wstrb;
    logic                    m7_wlast;
    logic                    m7_wvalid;
    logic                    m7_wready;
    
    logic [ID_WIDTH-1:0]     m7_bid;
    logic [1:0]              m7_bresp;
    logic                    m7_bvalid;
    logic                    m7_bready;
    
    logic [ID_WIDTH-1:0]     m7_arid;
    logic [ADDR_WIDTH-1:0]   m7_araddr;
    logic [7:0]              m7_arlen;
    logic [2:0]              m7_arsize;
    logic [1:0]              m7_arburst;
    logic                    m7_arlock;
    logic [3:0]              m7_arcache;
    logic [2:0]              m7_arprot;
    logic [3:0]              m7_arqos;
    logic                    m7_arvalid;
    logic                    m7_arready;
    
    logic [ID_WIDTH-1:0]     m7_rid;
    logic [DATA_WIDTH-1:0]   m7_rdata;
    logic [1:0]              m7_rresp;
    logic                    m7_rlast;
    logic                    m7_rvalid;
    logic                    m7_rready;

    // Master 8 signals
    logic [ID_WIDTH-1:0]     m8_awid;
    logic [ADDR_WIDTH-1:0]   m8_awaddr;
    logic [7:0]              m8_awlen;
    logic [2:0]              m8_awsize;
    logic [1:0]              m8_awburst;
    logic                    m8_awlock;
    logic [3:0]              m8_awcache;
    logic [2:0]              m8_awprot;
    logic [3:0]              m8_awqos;
    logic                    m8_awvalid;
    logic                    m8_awready;
    
    logic [DATA_WIDTH-1:0]   m8_wdata;
    logic [DATA_WIDTH/8-1:0] m8_wstrb;
    logic                    m8_wlast;
    logic                    m8_wvalid;
    logic                    m8_wready;
    
    logic [ID_WIDTH-1:0]     m8_bid;
    logic [1:0]              m8_bresp;
    logic                    m8_bvalid;
    logic                    m8_bready;
    
    logic [ID_WIDTH-1:0]     m8_arid;
    logic [ADDR_WIDTH-1:0]   m8_araddr;
    logic [7:0]              m8_arlen;
    logic [2:0]              m8_arsize;
    logic [1:0]              m8_arburst;
    logic                    m8_arlock;
    logic [3:0]              m8_arcache;
    logic [2:0]              m8_arprot;
    logic [3:0]              m8_arqos;
    logic                    m8_arvalid;
    logic                    m8_arready;
    
    logic [ID_WIDTH-1:0]     m8_rid;
    logic [DATA_WIDTH-1:0]   m8_rdata;
    logic [1:0]              m8_rresp;
    logic                    m8_rlast;
    logic                    m8_rvalid;
    logic                    m8_rready;

    
    // Internal signals for all slaves  
    // Slave 0 signals
    logic [ID_WIDTH-1:0]    s0_awid;
    logic [3:0]              s0_awcache;
    logic [2:0]              s0_awprot;
    logic [3:0]              s0_awqos;
    logic [ADDR_WIDTH-1:0]   s0_awaddr;
    logic [7:0]              s0_awlen;
    logic [2:0]              s0_awsize;
    logic [1:0]              s0_awburst;
    logic                    s0_awlock;
    logic                    s0_awvalid;
    logic                    s0_awready;
    
    logic [DATA_WIDTH-1:0]   s0_wdata;
    logic [DATA_WIDTH/8-1:0] s0_wstrb;
    logic                    s0_wlast;
    logic                    s0_wvalid;
    logic                    s0_wready;
    
    logic [ID_WIDTH-1:0]    s0_bid;
    logic [1:0]              s0_bresp;
    logic                    s0_bvalid;
    logic                    s0_bready;
    
    logic [ID_WIDTH-1:0]    s0_arid;
    logic [3:0]              s0_arcache;
    logic [2:0]              s0_arprot;
    logic [3:0]              s0_arqos;
    logic [ADDR_WIDTH-1:0]   s0_araddr;
    logic [7:0]              s0_arlen;
    logic [2:0]              s0_arsize;
    logic [1:0]              s0_arburst;
    logic                    s0_arlock;
    logic                    s0_arvalid;
    logic                    s0_arready;
    
    logic [ID_WIDTH-1:0]    s0_rid;
    logic [DATA_WIDTH-1:0]   s0_rdata;
    logic [1:0]              s0_rresp;
    logic                    s0_rlast;
    logic                    s0_rvalid;
    logic                    s0_rready;

    // Slave 1 signals
    logic [ID_WIDTH-1:0]    s1_awid;
    logic [3:0]              s1_awcache;
    logic [2:0]              s1_awprot;
    logic [3:0]              s1_awqos;
    logic [ADDR_WIDTH-1:0]   s1_awaddr;
    logic [7:0]              s1_awlen;
    logic [2:0]              s1_awsize;
    logic [1:0]              s1_awburst;
    logic                    s1_awlock;
    logic                    s1_awvalid;
    logic                    s1_awready;
    
    logic [DATA_WIDTH-1:0]   s1_wdata;
    logic [DATA_WIDTH/8-1:0] s1_wstrb;
    logic                    s1_wlast;
    logic                    s1_wvalid;
    logic                    s1_wready;
    
    logic [ID_WIDTH-1:0]    s1_bid;
    logic [1:0]              s1_bresp;
    logic                    s1_bvalid;
    logic                    s1_bready;
    
    logic [ID_WIDTH-1:0]    s1_arid;
    logic [3:0]              s1_arcache;
    logic [2:0]              s1_arprot;
    logic [3:0]              s1_arqos;
    logic [ADDR_WIDTH-1:0]   s1_araddr;
    logic [7:0]              s1_arlen;
    logic [2:0]              s1_arsize;
    logic [1:0]              s1_arburst;
    logic                    s1_arlock;
    logic                    s1_arvalid;
    logic                    s1_arready;
    
    logic [ID_WIDTH-1:0]    s1_rid;
    logic [DATA_WIDTH-1:0]   s1_rdata;
    logic [1:0]              s1_rresp;
    logic                    s1_rlast;
    logic                    s1_rvalid;
    logic                    s1_rready;

    // Slave 2 signals
    logic [ID_WIDTH-1:0]    s2_awid;
    logic [3:0]              s2_awcache;
    logic [2:0]              s2_awprot;
    logic [3:0]              s2_awqos;
    logic [ADDR_WIDTH-1:0]   s2_awaddr;
    logic [7:0]              s2_awlen;
    logic [2:0]              s2_awsize;
    logic [1:0]              s2_awburst;
    logic                    s2_awlock;
    logic                    s2_awvalid;
    logic                    s2_awready;
    
    logic [DATA_WIDTH-1:0]   s2_wdata;
    logic [DATA_WIDTH/8-1:0] s2_wstrb;
    logic                    s2_wlast;
    logic                    s2_wvalid;
    logic                    s2_wready;
    
    logic [ID_WIDTH-1:0]    s2_bid;
    logic [1:0]              s2_bresp;
    logic                    s2_bvalid;
    logic                    s2_bready;
    
    logic [ID_WIDTH-1:0]    s2_arid;
    logic [3:0]              s2_arcache;
    logic [2:0]              s2_arprot;
    logic [3:0]              s2_arqos;
    logic [ADDR_WIDTH-1:0]   s2_araddr;
    logic [7:0]              s2_arlen;
    logic [2:0]              s2_arsize;
    logic [1:0]              s2_arburst;
    logic                    s2_arlock;
    logic                    s2_arvalid;
    logic                    s2_arready;
    
    logic [ID_WIDTH-1:0]    s2_rid;
    logic [DATA_WIDTH-1:0]   s2_rdata;
    logic [1:0]              s2_rresp;
    logic                    s2_rlast;
    logic                    s2_rvalid;
    logic                    s2_rready;

    // Slave 3 signals
    logic [ID_WIDTH-1:0]    s3_awid;
    logic [3:0]              s3_awcache;
    logic [2:0]              s3_awprot;
    logic [3:0]              s3_awqos;
    logic [ADDR_WIDTH-1:0]   s3_awaddr;
    logic [7:0]              s3_awlen;
    logic [2:0]              s3_awsize;
    logic [1:0]              s3_awburst;
    logic                    s3_awlock;
    logic                    s3_awvalid;
    logic                    s3_awready;
    
    logic [DATA_WIDTH-1:0]   s3_wdata;
    logic [DATA_WIDTH/8-1:0] s3_wstrb;
    logic                    s3_wlast;
    logic                    s3_wvalid;
    logic                    s3_wready;
    
    logic [ID_WIDTH-1:0]    s3_bid;
    logic [1:0]              s3_bresp;
    logic                    s3_bvalid;
    logic                    s3_bready;
    
    logic [ID_WIDTH-1:0]    s3_arid;
    logic [3:0]              s3_arcache;
    logic [2:0]              s3_arprot;
    logic [3:0]              s3_arqos;
    logic [ADDR_WIDTH-1:0]   s3_araddr;
    logic [7:0]              s3_arlen;
    logic [2:0]              s3_arsize;
    logic [1:0]              s3_arburst;
    logic                    s3_arlock;
    logic                    s3_arvalid;
    logic                    s3_arready;
    
    logic [ID_WIDTH-1:0]    s3_rid;
    logic [DATA_WIDTH-1:0]   s3_rdata;
    logic [1:0]              s3_rresp;
    logic                    s3_rlast;
    logic                    s3_rvalid;
    logic                    s3_rready;

    // Slave 4 signals
    logic [ID_WIDTH-1:0]    s4_awid;
    logic [3:0]              s4_awcache;
    logic [2:0]              s4_awprot;
    logic [3:0]              s4_awqos;
    logic [ADDR_WIDTH-1:0]   s4_awaddr;
    logic [7:0]              s4_awlen;
    logic [2:0]              s4_awsize;
    logic [1:0]              s4_awburst;
    logic                    s4_awlock;
    logic                    s4_awvalid;
    logic                    s4_awready;
    
    logic [DATA_WIDTH-1:0]   s4_wdata;
    logic [DATA_WIDTH/8-1:0] s4_wstrb;
    logic                    s4_wlast;
    logic                    s4_wvalid;
    logic                    s4_wready;
    
    logic [ID_WIDTH-1:0]    s4_bid;
    logic [1:0]              s4_bresp;
    logic                    s4_bvalid;
    logic                    s4_bready;
    
    logic [ID_WIDTH-1:0]    s4_arid;
    logic [3:0]              s4_arcache;
    logic [2:0]              s4_arprot;
    logic [3:0]              s4_arqos;
    logic [ADDR_WIDTH-1:0]   s4_araddr;
    logic [7:0]              s4_arlen;
    logic [2:0]              s4_arsize;
    logic [1:0]              s4_arburst;
    logic                    s4_arlock;
    logic                    s4_arvalid;
    logic                    s4_arready;
    
    logic [ID_WIDTH-1:0]    s4_rid;
    logic [DATA_WIDTH-1:0]   s4_rdata;
    logic [1:0]              s4_rresp;
    logic                    s4_rlast;
    logic                    s4_rvalid;
    logic                    s4_rready;

    // Slave 5 signals
    logic [ID_WIDTH-1:0]    s5_awid;
    logic [3:0]              s5_awcache;
    logic [2:0]              s5_awprot;
    logic [3:0]              s5_awqos;
    logic [ADDR_WIDTH-1:0]   s5_awaddr;
    logic [7:0]              s5_awlen;
    logic [2:0]              s5_awsize;
    logic [1:0]              s5_awburst;
    logic                    s5_awlock;
    logic                    s5_awvalid;
    logic                    s5_awready;
    
    logic [DATA_WIDTH-1:0]   s5_wdata;
    logic [DATA_WIDTH/8-1:0] s5_wstrb;
    logic                    s5_wlast;
    logic                    s5_wvalid;
    logic                    s5_wready;
    
    logic [ID_WIDTH-1:0]    s5_bid;
    logic [1:0]              s5_bresp;
    logic                    s5_bvalid;
    logic                    s5_bready;
    
    logic [ID_WIDTH-1:0]    s5_arid;
    logic [3:0]              s5_arcache;
    logic [2:0]              s5_arprot;
    logic [3:0]              s5_arqos;
    logic [ADDR_WIDTH-1:0]   s5_araddr;
    logic [7:0]              s5_arlen;
    logic [2:0]              s5_arsize;
    logic [1:0]              s5_arburst;
    logic                    s5_arlock;
    logic                    s5_arvalid;
    logic                    s5_arready;
    
    logic [ID_WIDTH-1:0]    s5_rid;
    logic [DATA_WIDTH-1:0]   s5_rdata;
    logic [1:0]              s5_rresp;
    logic                    s5_rlast;
    logic                    s5_rvalid;
    logic                    s5_rready;

    // Slave 6 signals
    logic [ID_WIDTH-1:0]    s6_awid;
    logic [3:0]              s6_awcache;
    logic [2:0]              s6_awprot;
    logic [3:0]              s6_awqos;
    logic [ADDR_WIDTH-1:0]   s6_awaddr;
    logic [7:0]              s6_awlen;
    logic [2:0]              s6_awsize;
    logic [1:0]              s6_awburst;
    logic                    s6_awlock;
    logic                    s6_awvalid;
    logic                    s6_awready;
    
    logic [DATA_WIDTH-1:0]   s6_wdata;
    logic [DATA_WIDTH/8-1:0] s6_wstrb;
    logic                    s6_wlast;
    logic                    s6_wvalid;
    logic                    s6_wready;
    
    logic [ID_WIDTH-1:0]    s6_bid;
    logic [1:0]              s6_bresp;
    logic                    s6_bvalid;
    logic                    s6_bready;
    
    logic [ID_WIDTH-1:0]    s6_arid;
    logic [3:0]              s6_arcache;
    logic [2:0]              s6_arprot;
    logic [3:0]              s6_arqos;
    logic [ADDR_WIDTH-1:0]   s6_araddr;
    logic [7:0]              s6_arlen;
    logic [2:0]              s6_arsize;
    logic [1:0]              s6_arburst;
    logic                    s6_arlock;
    logic                    s6_arvalid;
    logic                    s6_arready;
    
    logic [ID_WIDTH-1:0]    s6_rid;
    logic [DATA_WIDTH-1:0]   s6_rdata;
    logic [1:0]              s6_rresp;
    logic                    s6_rlast;
    logic                    s6_rvalid;
    logic                    s6_rready;

    // Slave 7 signals
    logic [ID_WIDTH-1:0]    s7_awid;
    logic [3:0]              s7_awcache;
    logic [2:0]              s7_awprot;
    logic [3:0]              s7_awqos;
    logic [ADDR_WIDTH-1:0]   s7_awaddr;
    logic [7:0]              s7_awlen;
    logic [2:0]              s7_awsize;
    logic [1:0]              s7_awburst;
    logic                    s7_awlock;
    logic                    s7_awvalid;
    logic                    s7_awready;
    
    logic [DATA_WIDTH-1:0]   s7_wdata;
    logic [DATA_WIDTH/8-1:0] s7_wstrb;
    logic                    s7_wlast;
    logic                    s7_wvalid;
    logic                    s7_wready;
    
    logic [ID_WIDTH-1:0]    s7_bid;
    logic [1:0]              s7_bresp;
    logic                    s7_bvalid;
    logic                    s7_bready;
    
    logic [ID_WIDTH-1:0]    s7_arid;
    logic [3:0]              s7_arcache;
    logic [2:0]              s7_arprot;
    logic [3:0]              s7_arqos;
    logic [ADDR_WIDTH-1:0]   s7_araddr;
    logic [7:0]              s7_arlen;
    logic [2:0]              s7_arsize;
    logic [1:0]              s7_arburst;
    logic                    s7_arlock;
    logic                    s7_arvalid;
    logic                    s7_arready;
    
    logic [ID_WIDTH-1:0]    s7_rid;
    logic [DATA_WIDTH-1:0]   s7_rdata;
    logic [1:0]              s7_rresp;
    logic                    s7_rlast;
    logic                    s7_rvalid;
    logic                    s7_rready;

    // Slave 8 signals
    logic [ID_WIDTH-1:0]    s8_awid;
    logic [3:0]              s8_awcache;
    logic [2:0]              s8_awprot;
    logic [3:0]              s8_awqos;
    logic [ADDR_WIDTH-1:0]   s8_awaddr;
    logic [7:0]              s8_awlen;
    logic [2:0]              s8_awsize;
    logic [1:0]              s8_awburst;
    logic                    s8_awlock;
    logic                    s8_awvalid;
    logic                    s8_awready;
    
    logic [DATA_WIDTH-1:0]   s8_wdata;
    logic [DATA_WIDTH/8-1:0] s8_wstrb;
    logic                    s8_wlast;
    logic                    s8_wvalid;
    logic                    s8_wready;
    
    logic [ID_WIDTH-1:0]    s8_bid;
    logic [1:0]              s8_bresp;
    logic                    s8_bvalid;
    logic                    s8_bready;
    
    logic [ID_WIDTH-1:0]    s8_arid;
    logic [3:0]              s8_arcache;
    logic [2:0]              s8_arprot;
    logic [3:0]              s8_arqos;
    logic [ADDR_WIDTH-1:0]   s8_araddr;
    logic [7:0]              s8_arlen;
    logic [2:0]              s8_arsize;
    logic [1:0]              s8_arburst;
    logic                    s8_arlock;
    logic                    s8_arvalid;
    logic                    s8_arready;
    
    logic [ID_WIDTH-1:0]    s8_rid;
    logic [DATA_WIDTH-1:0]   s8_rdata;
    logic [1:0]              s8_rresp;
    logic                    s8_rlast;
    logic                    s8_rvalid;
    logic                    s8_rready;


    // Instantiate the generated interconnect
    axi4_interconnect_m9s9 #(
        .DATA_WIDTH(DATA_WIDTH),
        .ADDR_WIDTH(ADDR_WIDTH),
        .ID_WIDTH(ID_WIDTH)
    ) generated_interconnect (
        .aclk(clk),
        .aresetn(rst_n),
        
        // Master 0 - CPU0
        .m0_awid(m0_awid),
        .m0_awaddr(m0_awaddr),
        .m0_awlen(m0_awlen),
        .m0_awsize(m0_awsize),
        .m0_awburst(m0_awburst),
        .m0_awlock(m0_awlock),
        .m0_awcache(m0_awcache),
        .m0_awprot(m0_awprot),
        .m0_awqos(m0_awqos),
        .m0_awvalid(m0_awvalid),
        .m0_awready(m0_awready),
        
        .m0_wdata(m0_wdata),
        .m0_wstrb(m0_wstrb),
        .m0_wlast(m0_wlast),
        .m0_wvalid(m0_wvalid),
        .m0_wready(m0_wready),
        
        .m0_bid(m0_bid),
        .m0_bresp(m0_bresp),
        .m0_bvalid(m0_bvalid),
        .m0_bready(m0_bready),
        
        .m0_arid(m0_arid),
        .m0_araddr(m0_araddr),
        .m0_arlen(m0_arlen),
        .m0_arsize(m0_arsize),
        .m0_arburst(m0_arburst),
        .m0_arlock(m0_arlock),
        .m0_arcache(m0_arcache),
        .m0_arprot(m0_arprot),
        .m0_arqos(m0_arqos),
        .m0_arvalid(m0_arvalid),
        .m0_arready(m0_arready),
        
        .m0_rid(m0_rid),
        .m0_rdata(m0_rdata),
        .m0_rresp(m0_rresp),
        .m0_rlast(m0_rlast),
        .m0_rvalid(m0_rvalid),
        .m0_rready(m0_rready),
        // Master 1 - CPU1
        .m1_awid(m1_awid),
        .m1_awaddr(m1_awaddr),
        .m1_awlen(m1_awlen),
        .m1_awsize(m1_awsize),
        .m1_awburst(m1_awburst),
        .m1_awlock(m1_awlock),
        .m1_awcache(m1_awcache),
        .m1_awprot(m1_awprot),
        .m1_awqos(m1_awqos),
        .m1_awvalid(m1_awvalid),
        .m1_awready(m1_awready),
        
        .m1_wdata(m1_wdata),
        .m1_wstrb(m1_wstrb),
        .m1_wlast(m1_wlast),
        .m1_wvalid(m1_wvalid),
        .m1_wready(m1_wready),
        
        .m1_bid(m1_bid),
        .m1_bresp(m1_bresp),
        .m1_bvalid(m1_bvalid),
        .m1_bready(m1_bready),
        
        .m1_arid(m1_arid),
        .m1_araddr(m1_araddr),
        .m1_arlen(m1_arlen),
        .m1_arsize(m1_arsize),
        .m1_arburst(m1_arburst),
        .m1_arlock(m1_arlock),
        .m1_arcache(m1_arcache),
        .m1_arprot(m1_arprot),
        .m1_arqos(m1_arqos),
        .m1_arvalid(m1_arvalid),
        .m1_arready(m1_arready),
        
        .m1_rid(m1_rid),
        .m1_rdata(m1_rdata),
        .m1_rresp(m1_rresp),
        .m1_rlast(m1_rlast),
        .m1_rvalid(m1_rvalid),
        .m1_rready(m1_rready),
        // Master 2 - GPU
        .m2_awid(m2_awid),
        .m2_awaddr(m2_awaddr),
        .m2_awlen(m2_awlen),
        .m2_awsize(m2_awsize),
        .m2_awburst(m2_awburst),
        .m2_awlock(m2_awlock),
        .m2_awcache(m2_awcache),
        .m2_awprot(m2_awprot),
        .m2_awqos(m2_awqos),
        .m2_awvalid(m2_awvalid),
        .m2_awready(m2_awready),
        
        .m2_wdata(m2_wdata),
        .m2_wstrb(m2_wstrb),
        .m2_wlast(m2_wlast),
        .m2_wvalid(m2_wvalid),
        .m2_wready(m2_wready),
        
        .m2_bid(m2_bid),
        .m2_bresp(m2_bresp),
        .m2_bvalid(m2_bvalid),
        .m2_bready(m2_bready),
        
        .m2_arid(m2_arid),
        .m2_araddr(m2_araddr),
        .m2_arlen(m2_arlen),
        .m2_arsize(m2_arsize),
        .m2_arburst(m2_arburst),
        .m2_arlock(m2_arlock),
        .m2_arcache(m2_arcache),
        .m2_arprot(m2_arprot),
        .m2_arqos(m2_arqos),
        .m2_arvalid(m2_arvalid),
        .m2_arready(m2_arready),
        
        .m2_rid(m2_rid),
        .m2_rdata(m2_rdata),
        .m2_rresp(m2_rresp),
        .m2_rlast(m2_rlast),
        .m2_rvalid(m2_rvalid),
        .m2_rready(m2_rready),
        // Master 3 - DMA0
        .m3_awid(m3_awid),
        .m3_awaddr(m3_awaddr),
        .m3_awlen(m3_awlen),
        .m3_awsize(m3_awsize),
        .m3_awburst(m3_awburst),
        .m3_awlock(m3_awlock),
        .m3_awcache(m3_awcache),
        .m3_awprot(m3_awprot),
        .m3_awqos(m3_awqos),
        .m3_awvalid(m3_awvalid),
        .m3_awready(m3_awready),
        
        .m3_wdata(m3_wdata),
        .m3_wstrb(m3_wstrb),
        .m3_wlast(m3_wlast),
        .m3_wvalid(m3_wvalid),
        .m3_wready(m3_wready),
        
        .m3_bid(m3_bid),
        .m3_bresp(m3_bresp),
        .m3_bvalid(m3_bvalid),
        .m3_bready(m3_bready),
        
        .m3_arid(m3_arid),
        .m3_araddr(m3_araddr),
        .m3_arlen(m3_arlen),
        .m3_arsize(m3_arsize),
        .m3_arburst(m3_arburst),
        .m3_arlock(m3_arlock),
        .m3_arcache(m3_arcache),
        .m3_arprot(m3_arprot),
        .m3_arqos(m3_arqos),
        .m3_arvalid(m3_arvalid),
        .m3_arready(m3_arready),
        
        .m3_rid(m3_rid),
        .m3_rdata(m3_rdata),
        .m3_rresp(m3_rresp),
        .m3_rlast(m3_rlast),
        .m3_rvalid(m3_rvalid),
        .m3_rready(m3_rready),
        // Master 4 - DMA1
        .m4_awid(m4_awid),
        .m4_awaddr(m4_awaddr),
        .m4_awlen(m4_awlen),
        .m4_awsize(m4_awsize),
        .m4_awburst(m4_awburst),
        .m4_awlock(m4_awlock),
        .m4_awcache(m4_awcache),
        .m4_awprot(m4_awprot),
        .m4_awqos(m4_awqos),
        .m4_awvalid(m4_awvalid),
        .m4_awready(m4_awready),
        
        .m4_wdata(m4_wdata),
        .m4_wstrb(m4_wstrb),
        .m4_wlast(m4_wlast),
        .m4_wvalid(m4_wvalid),
        .m4_wready(m4_wready),
        
        .m4_bid(m4_bid),
        .m4_bresp(m4_bresp),
        .m4_bvalid(m4_bvalid),
        .m4_bready(m4_bready),
        
        .m4_arid(m4_arid),
        .m4_araddr(m4_araddr),
        .m4_arlen(m4_arlen),
        .m4_arsize(m4_arsize),
        .m4_arburst(m4_arburst),
        .m4_arlock(m4_arlock),
        .m4_arcache(m4_arcache),
        .m4_arprot(m4_arprot),
        .m4_arqos(m4_arqos),
        .m4_arvalid(m4_arvalid),
        .m4_arready(m4_arready),
        
        .m4_rid(m4_rid),
        .m4_rdata(m4_rdata),
        .m4_rresp(m4_rresp),
        .m4_rlast(m4_rlast),
        .m4_rvalid(m4_rvalid),
        .m4_rready(m4_rready),
        // Master 5 - VIDEO
        .m5_awid(m5_awid),
        .m5_awaddr(m5_awaddr),
        .m5_awlen(m5_awlen),
        .m5_awsize(m5_awsize),
        .m5_awburst(m5_awburst),
        .m5_awlock(m5_awlock),
        .m5_awcache(m5_awcache),
        .m5_awprot(m5_awprot),
        .m5_awqos(m5_awqos),
        .m5_awvalid(m5_awvalid),
        .m5_awready(m5_awready),
        
        .m5_wdata(m5_wdata),
        .m5_wstrb(m5_wstrb),
        .m5_wlast(m5_wlast),
        .m5_wvalid(m5_wvalid),
        .m5_wready(m5_wready),
        
        .m5_bid(m5_bid),
        .m5_bresp(m5_bresp),
        .m5_bvalid(m5_bvalid),
        .m5_bready(m5_bready),
        
        .m5_arid(m5_arid),
        .m5_araddr(m5_araddr),
        .m5_arlen(m5_arlen),
        .m5_arsize(m5_arsize),
        .m5_arburst(m5_arburst),
        .m5_arlock(m5_arlock),
        .m5_arcache(m5_arcache),
        .m5_arprot(m5_arprot),
        .m5_arqos(m5_arqos),
        .m5_arvalid(m5_arvalid),
        .m5_arready(m5_arready),
        
        .m5_rid(m5_rid),
        .m5_rdata(m5_rdata),
        .m5_rresp(m5_rresp),
        .m5_rlast(m5_rlast),
        .m5_rvalid(m5_rvalid),
        .m5_rready(m5_rready),
        // Master 6 - AUDIO
        .m6_awid(m6_awid),
        .m6_awaddr(m6_awaddr),
        .m6_awlen(m6_awlen),
        .m6_awsize(m6_awsize),
        .m6_awburst(m6_awburst),
        .m6_awlock(m6_awlock),
        .m6_awcache(m6_awcache),
        .m6_awprot(m6_awprot),
        .m6_awqos(m6_awqos),
        .m6_awvalid(m6_awvalid),
        .m6_awready(m6_awready),
        
        .m6_wdata(m6_wdata),
        .m6_wstrb(m6_wstrb),
        .m6_wlast(m6_wlast),
        .m6_wvalid(m6_wvalid),
        .m6_wready(m6_wready),
        
        .m6_bid(m6_bid),
        .m6_bresp(m6_bresp),
        .m6_bvalid(m6_bvalid),
        .m6_bready(m6_bready),
        
        .m6_arid(m6_arid),
        .m6_araddr(m6_araddr),
        .m6_arlen(m6_arlen),
        .m6_arsize(m6_arsize),
        .m6_arburst(m6_arburst),
        .m6_arlock(m6_arlock),
        .m6_arcache(m6_arcache),
        .m6_arprot(m6_arprot),
        .m6_arqos(m6_arqos),
        .m6_arvalid(m6_arvalid),
        .m6_arready(m6_arready),
        
        .m6_rid(m6_rid),
        .m6_rdata(m6_rdata),
        .m6_rresp(m6_rresp),
        .m6_rlast(m6_rlast),
        .m6_rvalid(m6_rvalid),
        .m6_rready(m6_rready),
        // Master 7 - USB
        .m7_awid(m7_awid),
        .m7_awaddr(m7_awaddr),
        .m7_awlen(m7_awlen),
        .m7_awsize(m7_awsize),
        .m7_awburst(m7_awburst),
        .m7_awlock(m7_awlock),
        .m7_awcache(m7_awcache),
        .m7_awprot(m7_awprot),
        .m7_awqos(m7_awqos),
        .m7_awvalid(m7_awvalid),
        .m7_awready(m7_awready),
        
        .m7_wdata(m7_wdata),
        .m7_wstrb(m7_wstrb),
        .m7_wlast(m7_wlast),
        .m7_wvalid(m7_wvalid),
        .m7_wready(m7_wready),
        
        .m7_bid(m7_bid),
        .m7_bresp(m7_bresp),
        .m7_bvalid(m7_bvalid),
        .m7_bready(m7_bready),
        
        .m7_arid(m7_arid),
        .m7_araddr(m7_araddr),
        .m7_arlen(m7_arlen),
        .m7_arsize(m7_arsize),
        .m7_arburst(m7_arburst),
        .m7_arlock(m7_arlock),
        .m7_arcache(m7_arcache),
        .m7_arprot(m7_arprot),
        .m7_arqos(m7_arqos),
        .m7_arvalid(m7_arvalid),
        .m7_arready(m7_arready),
        
        .m7_rid(m7_rid),
        .m7_rdata(m7_rdata),
        .m7_rresp(m7_rresp),
        .m7_rlast(m7_rlast),
        .m7_rvalid(m7_rvalid),
        .m7_rready(m7_rready),
        // Master 8 - ENET
        .m8_awid(m8_awid),
        .m8_awaddr(m8_awaddr),
        .m8_awlen(m8_awlen),
        .m8_awsize(m8_awsize),
        .m8_awburst(m8_awburst),
        .m8_awlock(m8_awlock),
        .m8_awcache(m8_awcache),
        .m8_awprot(m8_awprot),
        .m8_awqos(m8_awqos),
        .m8_awvalid(m8_awvalid),
        .m8_awready(m8_awready),
        
        .m8_wdata(m8_wdata),
        .m8_wstrb(m8_wstrb),
        .m8_wlast(m8_wlast),
        .m8_wvalid(m8_wvalid),
        .m8_wready(m8_wready),
        
        .m8_bid(m8_bid),
        .m8_bresp(m8_bresp),
        .m8_bvalid(m8_bvalid),
        .m8_bready(m8_bready),
        
        .m8_arid(m8_arid),
        .m8_araddr(m8_araddr),
        .m8_arlen(m8_arlen),
        .m8_arsize(m8_arsize),
        .m8_arburst(m8_arburst),
        .m8_arlock(m8_arlock),
        .m8_arcache(m8_arcache),
        .m8_arprot(m8_arprot),
        .m8_arqos(m8_arqos),
        .m8_arvalid(m8_arvalid),
        .m8_arready(m8_arready),
        
        .m8_rid(m8_rid),
        .m8_rdata(m8_rdata),
        .m8_rresp(m8_rresp),
        .m8_rlast(m8_rlast),
        .m8_rvalid(m8_rvalid),
        .m8_rready(m8_rready),
        
        // Slave 0 - DDR0
        .s0_awid(s0_awid),
        .s0_awaddr(s0_awaddr),
        .s0_awlen(s0_awlen),
        .s0_awsize(s0_awsize),
        .s0_awburst(s0_awburst),
        .s0_awlock(s0_awlock),
        .s0_awvalid(s0_awvalid),
        .s0_awready(s0_awready),
        .s0_awcache(s0_awcache),
        .s0_awprot(s0_awprot),
        .s0_awqos(s0_awqos),
        
        .s0_wdata(s0_wdata),
        .s0_wstrb(s0_wstrb),
        .s0_wlast(s0_wlast),
        .s0_wvalid(s0_wvalid),
        .s0_wready(s0_wready),
        
        .s0_bid(s0_bid),
        .s0_bresp(s0_bresp),
        .s0_bvalid(s0_bvalid),
        .s0_bready(s0_bready),
        
        .s0_arid(s0_arid),
        .s0_araddr(s0_araddr),
        .s0_arlen(s0_arlen),
        .s0_arsize(s0_arsize),
        .s0_arburst(s0_arburst),
        .s0_arlock(s0_arlock),
        .s0_arvalid(s0_arvalid),
        .s0_arready(s0_arready),
        .s0_arcache(s0_arcache),
        .s0_arprot(s0_arprot),
        .s0_arqos(s0_arqos),
        
        .s0_rid(s0_rid),
        .s0_rdata(s0_rdata),
        .s0_rresp(s0_rresp),
        .s0_rlast(s0_rlast),
        .s0_rvalid(s0_rvalid),
        .s0_rready(s0_rready)
,
        // Slave 1 - DDR1
        .s1_awid(s1_awid),
        .s1_awaddr(s1_awaddr),
        .s1_awlen(s1_awlen),
        .s1_awsize(s1_awsize),
        .s1_awburst(s1_awburst),
        .s1_awlock(s1_awlock),
        .s1_awvalid(s1_awvalid),
        .s1_awready(s1_awready),
        .s1_awcache(s1_awcache),
        .s1_awprot(s1_awprot),
        .s1_awqos(s1_awqos),
        
        .s1_wdata(s1_wdata),
        .s1_wstrb(s1_wstrb),
        .s1_wlast(s1_wlast),
        .s1_wvalid(s1_wvalid),
        .s1_wready(s1_wready),
        
        .s1_bid(s1_bid),
        .s1_bresp(s1_bresp),
        .s1_bvalid(s1_bvalid),
        .s1_bready(s1_bready),
        
        .s1_arid(s1_arid),
        .s1_araddr(s1_araddr),
        .s1_arlen(s1_arlen),
        .s1_arsize(s1_arsize),
        .s1_arburst(s1_arburst),
        .s1_arlock(s1_arlock),
        .s1_arvalid(s1_arvalid),
        .s1_arready(s1_arready),
        .s1_arcache(s1_arcache),
        .s1_arprot(s1_arprot),
        .s1_arqos(s1_arqos),
        
        .s1_rid(s1_rid),
        .s1_rdata(s1_rdata),
        .s1_rresp(s1_rresp),
        .s1_rlast(s1_rlast),
        .s1_rvalid(s1_rvalid),
        .s1_rready(s1_rready)
,
        // Slave 2 - SRAM0
        .s2_awid(s2_awid),
        .s2_awaddr(s2_awaddr),
        .s2_awlen(s2_awlen),
        .s2_awsize(s2_awsize),
        .s2_awburst(s2_awburst),
        .s2_awlock(s2_awlock),
        .s2_awvalid(s2_awvalid),
        .s2_awready(s2_awready),
        .s2_awcache(s2_awcache),
        .s2_awprot(s2_awprot),
        .s2_awqos(s2_awqos),
        
        .s2_wdata(s2_wdata),
        .s2_wstrb(s2_wstrb),
        .s2_wlast(s2_wlast),
        .s2_wvalid(s2_wvalid),
        .s2_wready(s2_wready),
        
        .s2_bid(s2_bid),
        .s2_bresp(s2_bresp),
        .s2_bvalid(s2_bvalid),
        .s2_bready(s2_bready),
        
        .s2_arid(s2_arid),
        .s2_araddr(s2_araddr),
        .s2_arlen(s2_arlen),
        .s2_arsize(s2_arsize),
        .s2_arburst(s2_arburst),
        .s2_arlock(s2_arlock),
        .s2_arvalid(s2_arvalid),
        .s2_arready(s2_arready),
        .s2_arcache(s2_arcache),
        .s2_arprot(s2_arprot),
        .s2_arqos(s2_arqos),
        
        .s2_rid(s2_rid),
        .s2_rdata(s2_rdata),
        .s2_rresp(s2_rresp),
        .s2_rlast(s2_rlast),
        .s2_rvalid(s2_rvalid),
        .s2_rready(s2_rready)
,
        // Slave 3 - SRAM1
        .s3_awid(s3_awid),
        .s3_awaddr(s3_awaddr),
        .s3_awlen(s3_awlen),
        .s3_awsize(s3_awsize),
        .s3_awburst(s3_awburst),
        .s3_awlock(s3_awlock),
        .s3_awvalid(s3_awvalid),
        .s3_awready(s3_awready),
        .s3_awcache(s3_awcache),
        .s3_awprot(s3_awprot),
        .s3_awqos(s3_awqos),
        
        .s3_wdata(s3_wdata),
        .s3_wstrb(s3_wstrb),
        .s3_wlast(s3_wlast),
        .s3_wvalid(s3_wvalid),
        .s3_wready(s3_wready),
        
        .s3_bid(s3_bid),
        .s3_bresp(s3_bresp),
        .s3_bvalid(s3_bvalid),
        .s3_bready(s3_bready),
        
        .s3_arid(s3_arid),
        .s3_araddr(s3_araddr),
        .s3_arlen(s3_arlen),
        .s3_arsize(s3_arsize),
        .s3_arburst(s3_arburst),
        .s3_arlock(s3_arlock),
        .s3_arvalid(s3_arvalid),
        .s3_arready(s3_arready),
        .s3_arcache(s3_arcache),
        .s3_arprot(s3_arprot),
        .s3_arqos(s3_arqos),
        
        .s3_rid(s3_rid),
        .s3_rdata(s3_rdata),
        .s3_rresp(s3_rresp),
        .s3_rlast(s3_rlast),
        .s3_rvalid(s3_rvalid),
        .s3_rready(s3_rready)
,
        // Slave 4 - ROM
        .s4_awid(s4_awid),
        .s4_awaddr(s4_awaddr),
        .s4_awlen(s4_awlen),
        .s4_awsize(s4_awsize),
        .s4_awburst(s4_awburst),
        .s4_awlock(s4_awlock),
        .s4_awvalid(s4_awvalid),
        .s4_awready(s4_awready),
        .s4_awcache(s4_awcache),
        .s4_awprot(s4_awprot),
        .s4_awqos(s4_awqos),
        
        .s4_wdata(s4_wdata),
        .s4_wstrb(s4_wstrb),
        .s4_wlast(s4_wlast),
        .s4_wvalid(s4_wvalid),
        .s4_wready(s4_wready),
        
        .s4_bid(s4_bid),
        .s4_bresp(s4_bresp),
        .s4_bvalid(s4_bvalid),
        .s4_bready(s4_bready),
        
        .s4_arid(s4_arid),
        .s4_araddr(s4_araddr),
        .s4_arlen(s4_arlen),
        .s4_arsize(s4_arsize),
        .s4_arburst(s4_arburst),
        .s4_arlock(s4_arlock),
        .s4_arvalid(s4_arvalid),
        .s4_arready(s4_arready),
        .s4_arcache(s4_arcache),
        .s4_arprot(s4_arprot),
        .s4_arqos(s4_arqos),
        
        .s4_rid(s4_rid),
        .s4_rdata(s4_rdata),
        .s4_rresp(s4_rresp),
        .s4_rlast(s4_rlast),
        .s4_rvalid(s4_rvalid),
        .s4_rready(s4_rready)
,
        // Slave 5 - APB0
        .s5_awid(s5_awid),
        .s5_awaddr(s5_awaddr),
        .s5_awlen(s5_awlen),
        .s5_awsize(s5_awsize),
        .s5_awburst(s5_awburst),
        .s5_awlock(s5_awlock),
        .s5_awvalid(s5_awvalid),
        .s5_awready(s5_awready),
        .s5_awcache(s5_awcache),
        .s5_awprot(s5_awprot),
        .s5_awqos(s5_awqos),
        
        .s5_wdata(s5_wdata),
        .s5_wstrb(s5_wstrb),
        .s5_wlast(s5_wlast),
        .s5_wvalid(s5_wvalid),
        .s5_wready(s5_wready),
        
        .s5_bid(s5_bid),
        .s5_bresp(s5_bresp),
        .s5_bvalid(s5_bvalid),
        .s5_bready(s5_bready),
        
        .s5_arid(s5_arid),
        .s5_araddr(s5_araddr),
        .s5_arlen(s5_arlen),
        .s5_arsize(s5_arsize),
        .s5_arburst(s5_arburst),
        .s5_arlock(s5_arlock),
        .s5_arvalid(s5_arvalid),
        .s5_arready(s5_arready),
        .s5_arcache(s5_arcache),
        .s5_arprot(s5_arprot),
        .s5_arqos(s5_arqos),
        
        .s5_rid(s5_rid),
        .s5_rdata(s5_rdata),
        .s5_rresp(s5_rresp),
        .s5_rlast(s5_rlast),
        .s5_rvalid(s5_rvalid),
        .s5_rready(s5_rready)
,
        // Slave 6 - APB1
        .s6_awid(s6_awid),
        .s6_awaddr(s6_awaddr),
        .s6_awlen(s6_awlen),
        .s6_awsize(s6_awsize),
        .s6_awburst(s6_awburst),
        .s6_awlock(s6_awlock),
        .s6_awvalid(s6_awvalid),
        .s6_awready(s6_awready),
        .s6_awcache(s6_awcache),
        .s6_awprot(s6_awprot),
        .s6_awqos(s6_awqos),
        
        .s6_wdata(s6_wdata),
        .s6_wstrb(s6_wstrb),
        .s6_wlast(s6_wlast),
        .s6_wvalid(s6_wvalid),
        .s6_wready(s6_wready),
        
        .s6_bid(s6_bid),
        .s6_bresp(s6_bresp),
        .s6_bvalid(s6_bvalid),
        .s6_bready(s6_bready),
        
        .s6_arid(s6_arid),
        .s6_araddr(s6_araddr),
        .s6_arlen(s6_arlen),
        .s6_arsize(s6_arsize),
        .s6_arburst(s6_arburst),
        .s6_arlock(s6_arlock),
        .s6_arvalid(s6_arvalid),
        .s6_arready(s6_arready),
        .s6_arcache(s6_arcache),
        .s6_arprot(s6_arprot),
        .s6_arqos(s6_arqos),
        
        .s6_rid(s6_rid),
        .s6_rdata(s6_rdata),
        .s6_rresp(s6_rresp),
        .s6_rlast(s6_rlast),
        .s6_rvalid(s6_rvalid),
        .s6_rready(s6_rready)
,
        // Slave 7 - PCIe
        .s7_awid(s7_awid),
        .s7_awaddr(s7_awaddr),
        .s7_awlen(s7_awlen),
        .s7_awsize(s7_awsize),
        .s7_awburst(s7_awburst),
        .s7_awlock(s7_awlock),
        .s7_awvalid(s7_awvalid),
        .s7_awready(s7_awready),
        .s7_awcache(s7_awcache),
        .s7_awprot(s7_awprot),
        .s7_awqos(s7_awqos),
        
        .s7_wdata(s7_wdata),
        .s7_wstrb(s7_wstrb),
        .s7_wlast(s7_wlast),
        .s7_wvalid(s7_wvalid),
        .s7_wready(s7_wready),
        
        .s7_bid(s7_bid),
        .s7_bresp(s7_bresp),
        .s7_bvalid(s7_bvalid),
        .s7_bready(s7_bready),
        
        .s7_arid(s7_arid),
        .s7_araddr(s7_araddr),
        .s7_arlen(s7_arlen),
        .s7_arsize(s7_arsize),
        .s7_arburst(s7_arburst),
        .s7_arlock(s7_arlock),
        .s7_arvalid(s7_arvalid),
        .s7_arready(s7_arready),
        .s7_arcache(s7_arcache),
        .s7_arprot(s7_arprot),
        .s7_arqos(s7_arqos),
        
        .s7_rid(s7_rid),
        .s7_rdata(s7_rdata),
        .s7_rresp(s7_rresp),
        .s7_rlast(s7_rlast),
        .s7_rvalid(s7_rvalid),
        .s7_rready(s7_rready)
,
        // Slave 8 - CUSTOM
        .s8_awid(s8_awid),
        .s8_awaddr(s8_awaddr),
        .s8_awlen(s8_awlen),
        .s8_awsize(s8_awsize),
        .s8_awburst(s8_awburst),
        .s8_awlock(s8_awlock),
        .s8_awvalid(s8_awvalid),
        .s8_awready(s8_awready),
        .s8_awcache(s8_awcache),
        .s8_awprot(s8_awprot),
        .s8_awqos(s8_awqos),
        
        .s8_wdata(s8_wdata),
        .s8_wstrb(s8_wstrb),
        .s8_wlast(s8_wlast),
        .s8_wvalid(s8_wvalid),
        .s8_wready(s8_wready),
        
        .s8_bid(s8_bid),
        .s8_bresp(s8_bresp),
        .s8_bvalid(s8_bvalid),
        .s8_bready(s8_bready),
        
        .s8_arid(s8_arid),
        .s8_araddr(s8_araddr),
        .s8_arlen(s8_arlen),
        .s8_arsize(s8_arsize),
        .s8_arburst(s8_arburst),
        .s8_arlock(s8_arlock),
        .s8_arvalid(s8_arvalid),
        .s8_arready(s8_arready),
        .s8_arcache(s8_arcache),
        .s8_arprot(s8_arprot),
        .s8_arqos(s8_arqos),
        
        .s8_rid(s8_rid),
        .s8_rdata(s8_rdata),
        .s8_rresp(s8_rresp),
        .s8_rlast(s8_rlast),
        .s8_rvalid(s8_rvalid),
        .s8_rready(s8_rready)
    );
    
    // Connect VIP to Master 0
    assign m0_awid    = axi_if.awid;
    assign m0_awaddr  = axi_if.awaddr;
    assign m0_awlen   = axi_if.awlen;
    assign m0_awsize  = axi_if.awsize;
    assign m0_awburst = axi_if.awburst;
    assign m0_awlock  = axi_if.awlock;
    assign m0_awcache = axi_if.awcache;
    assign m0_awprot  = axi_if.awprot;
    assign m0_awqos   = 4'b0000;  // Default QoS
    assign m0_awvalid = axi_if.awvalid;
    assign axi_if.awready = m0_awready;
    
    assign m0_wdata  = axi_if.wdata;
    assign m0_wstrb  = axi_if.wstrb;
    assign m0_wlast  = axi_if.wlast;
    assign m0_wvalid = axi_if.wvalid;
    assign axi_if.wready = m0_wready;
    
    assign axi_if.bid    = m0_bid;
    assign axi_if.bresp  = m0_bresp;
    assign axi_if.bvalid = m0_bvalid;
    assign m0_bready = axi_if.bready;
    
    assign m0_arid    = axi_if.arid;
    assign m0_araddr  = axi_if.araddr;
    assign m0_arlen   = axi_if.arlen;
    assign m0_arsize  = axi_if.arsize;
    assign m0_arburst = axi_if.arburst;
    assign m0_arlock  = axi_if.arlock;
    assign m0_arcache = axi_if.arcache;
    assign m0_arprot  = axi_if.arprot;
    assign m0_arqos   = 4'b0000;  // Default QoS
    assign m0_arvalid = axi_if.arvalid;
    assign axi_if.arready = m0_arready;
    
    assign axi_if.rid    = m0_rid;
    assign axi_if.rdata  = m0_rdata;
    assign axi_if.rresp  = m0_rresp;
    assign axi_if.rlast  = m0_rlast;
    assign axi_if.rvalid = m0_rvalid;
    assign m0_rready = axi_if.rready;
    
    // Terminate unused master interfaces
    // Master 1 termination
    // Write Address Channel
    assign m1_awid    = {ID_WIDTH{1'b0}};
    assign m1_awaddr  = {ADDR_WIDTH{1'b0}};
    assign m1_awlen   = 8'd0;
    assign m1_awsize  = 3'd0;
    assign m1_awburst = 2'b01;
    assign m1_awlock  = 1'b0;
    assign m1_awcache = 4'b0000;
    assign m1_awprot  = 3'b000;
    assign m1_awqos   = 4'b0000;
    assign m1_awvalid = 1'b0;
    
    // Write Data Channel
    assign m1_wdata   = {DATA_WIDTH{1'b0}};
    assign m1_wstrb   = {(DATA_WIDTH/8){1'b0}};
    assign m1_wlast   = 1'b0;
    assign m1_wvalid  = 1'b0;
    
    // Write Response Channel
    assign m1_bready  = 1'b1;
    
    // Read Address Channel
    assign m1_arid    = {ID_WIDTH{1'b0}};
    assign m1_araddr  = {ADDR_WIDTH{1'b0}};
    assign m1_arlen   = 8'd0;
    assign m1_arsize  = 3'd0;
    assign m1_arburst = 2'b01;
    assign m1_arlock  = 1'b0;
    assign m1_arcache = 4'b0000;
    assign m1_arprot  = 3'b000;
    assign m1_arqos   = 4'b0000;
    assign m1_arvalid = 1'b0;
    
    // Read Data Channel
    assign m1_rready  = 1'b1;

    // Master 2 termination
    // Write Address Channel
    assign m2_awid    = {ID_WIDTH{1'b0}};
    assign m2_awaddr  = {ADDR_WIDTH{1'b0}};
    assign m2_awlen   = 8'd0;
    assign m2_awsize  = 3'd0;
    assign m2_awburst = 2'b01;
    assign m2_awlock  = 1'b0;
    assign m2_awcache = 4'b0000;
    assign m2_awprot  = 3'b000;
    assign m2_awqos   = 4'b0000;
    assign m2_awvalid = 1'b0;
    
    // Write Data Channel
    assign m2_wdata   = {DATA_WIDTH{1'b0}};
    assign m2_wstrb   = {(DATA_WIDTH/8){1'b0}};
    assign m2_wlast   = 1'b0;
    assign m2_wvalid  = 1'b0;
    
    // Write Response Channel
    assign m2_bready  = 1'b1;
    
    // Read Address Channel
    assign m2_arid    = {ID_WIDTH{1'b0}};
    assign m2_araddr  = {ADDR_WIDTH{1'b0}};
    assign m2_arlen   = 8'd0;
    assign m2_arsize  = 3'd0;
    assign m2_arburst = 2'b01;
    assign m2_arlock  = 1'b0;
    assign m2_arcache = 4'b0000;
    assign m2_arprot  = 3'b000;
    assign m2_arqos   = 4'b0000;
    assign m2_arvalid = 1'b0;
    
    // Read Data Channel
    assign m2_rready  = 1'b1;

    // Master 3 termination
    // Write Address Channel
    assign m3_awid    = {ID_WIDTH{1'b0}};
    assign m3_awaddr  = {ADDR_WIDTH{1'b0}};
    assign m3_awlen   = 8'd0;
    assign m3_awsize  = 3'd0;
    assign m3_awburst = 2'b01;
    assign m3_awlock  = 1'b0;
    assign m3_awcache = 4'b0000;
    assign m3_awprot  = 3'b000;
    assign m3_awqos   = 4'b0000;
    assign m3_awvalid = 1'b0;
    
    // Write Data Channel
    assign m3_wdata   = {DATA_WIDTH{1'b0}};
    assign m3_wstrb   = {(DATA_WIDTH/8){1'b0}};
    assign m3_wlast   = 1'b0;
    assign m3_wvalid  = 1'b0;
    
    // Write Response Channel
    assign m3_bready  = 1'b1;
    
    // Read Address Channel
    assign m3_arid    = {ID_WIDTH{1'b0}};
    assign m3_araddr  = {ADDR_WIDTH{1'b0}};
    assign m3_arlen   = 8'd0;
    assign m3_arsize  = 3'd0;
    assign m3_arburst = 2'b01;
    assign m3_arlock  = 1'b0;
    assign m3_arcache = 4'b0000;
    assign m3_arprot  = 3'b000;
    assign m3_arqos   = 4'b0000;
    assign m3_arvalid = 1'b0;
    
    // Read Data Channel
    assign m3_rready  = 1'b1;

    // Master 4 termination
    // Write Address Channel
    assign m4_awid    = {ID_WIDTH{1'b0}};
    assign m4_awaddr  = {ADDR_WIDTH{1'b0}};
    assign m4_awlen   = 8'd0;
    assign m4_awsize  = 3'd0;
    assign m4_awburst = 2'b01;
    assign m4_awlock  = 1'b0;
    assign m4_awcache = 4'b0000;
    assign m4_awprot  = 3'b000;
    assign m4_awqos   = 4'b0000;
    assign m4_awvalid = 1'b0;
    
    // Write Data Channel
    assign m4_wdata   = {DATA_WIDTH{1'b0}};
    assign m4_wstrb   = {(DATA_WIDTH/8){1'b0}};
    assign m4_wlast   = 1'b0;
    assign m4_wvalid  = 1'b0;
    
    // Write Response Channel
    assign m4_bready  = 1'b1;
    
    // Read Address Channel
    assign m4_arid    = {ID_WIDTH{1'b0}};
    assign m4_araddr  = {ADDR_WIDTH{1'b0}};
    assign m4_arlen   = 8'd0;
    assign m4_arsize  = 3'd0;
    assign m4_arburst = 2'b01;
    assign m4_arlock  = 1'b0;
    assign m4_arcache = 4'b0000;
    assign m4_arprot  = 3'b000;
    assign m4_arqos   = 4'b0000;
    assign m4_arvalid = 1'b0;
    
    // Read Data Channel
    assign m4_rready  = 1'b1;

    // Master 5 termination
    // Write Address Channel
    assign m5_awid    = {ID_WIDTH{1'b0}};
    assign m5_awaddr  = {ADDR_WIDTH{1'b0}};
    assign m5_awlen   = 8'd0;
    assign m5_awsize  = 3'd0;
    assign m5_awburst = 2'b01;
    assign m5_awlock  = 1'b0;
    assign m5_awcache = 4'b0000;
    assign m5_awprot  = 3'b000;
    assign m5_awqos   = 4'b0000;
    assign m5_awvalid = 1'b0;
    
    // Write Data Channel
    assign m5_wdata   = {DATA_WIDTH{1'b0}};
    assign m5_wstrb   = {(DATA_WIDTH/8){1'b0}};
    assign m5_wlast   = 1'b0;
    assign m5_wvalid  = 1'b0;
    
    // Write Response Channel
    assign m5_bready  = 1'b1;
    
    // Read Address Channel
    assign m5_arid    = {ID_WIDTH{1'b0}};
    assign m5_araddr  = {ADDR_WIDTH{1'b0}};
    assign m5_arlen   = 8'd0;
    assign m5_arsize  = 3'd0;
    assign m5_arburst = 2'b01;
    assign m5_arlock  = 1'b0;
    assign m5_arcache = 4'b0000;
    assign m5_arprot  = 3'b000;
    assign m5_arqos   = 4'b0000;
    assign m5_arvalid = 1'b0;
    
    // Read Data Channel
    assign m5_rready  = 1'b1;

    // Master 6 termination
    // Write Address Channel
    assign m6_awid    = {ID_WIDTH{1'b0}};
    assign m6_awaddr  = {ADDR_WIDTH{1'b0}};
    assign m6_awlen   = 8'd0;
    assign m6_awsize  = 3'd0;
    assign m6_awburst = 2'b01;
    assign m6_awlock  = 1'b0;
    assign m6_awcache = 4'b0000;
    assign m6_awprot  = 3'b000;
    assign m6_awqos   = 4'b0000;
    assign m6_awvalid = 1'b0;
    
    // Write Data Channel
    assign m6_wdata   = {DATA_WIDTH{1'b0}};
    assign m6_wstrb   = {(DATA_WIDTH/8){1'b0}};
    assign m6_wlast   = 1'b0;
    assign m6_wvalid  = 1'b0;
    
    // Write Response Channel
    assign m6_bready  = 1'b1;
    
    // Read Address Channel
    assign m6_arid    = {ID_WIDTH{1'b0}};
    assign m6_araddr  = {ADDR_WIDTH{1'b0}};
    assign m6_arlen   = 8'd0;
    assign m6_arsize  = 3'd0;
    assign m6_arburst = 2'b01;
    assign m6_arlock  = 1'b0;
    assign m6_arcache = 4'b0000;
    assign m6_arprot  = 3'b000;
    assign m6_arqos   = 4'b0000;
    assign m6_arvalid = 1'b0;
    
    // Read Data Channel
    assign m6_rready  = 1'b1;

    // Master 7 termination
    // Write Address Channel
    assign m7_awid    = {ID_WIDTH{1'b0}};
    assign m7_awaddr  = {ADDR_WIDTH{1'b0}};
    assign m7_awlen   = 8'd0;
    assign m7_awsize  = 3'd0;
    assign m7_awburst = 2'b01;
    assign m7_awlock  = 1'b0;
    assign m7_awcache = 4'b0000;
    assign m7_awprot  = 3'b000;
    assign m7_awqos   = 4'b0000;
    assign m7_awvalid = 1'b0;
    
    // Write Data Channel
    assign m7_wdata   = {DATA_WIDTH{1'b0}};
    assign m7_wstrb   = {(DATA_WIDTH/8){1'b0}};
    assign m7_wlast   = 1'b0;
    assign m7_wvalid  = 1'b0;
    
    // Write Response Channel
    assign m7_bready  = 1'b1;
    
    // Read Address Channel
    assign m7_arid    = {ID_WIDTH{1'b0}};
    assign m7_araddr  = {ADDR_WIDTH{1'b0}};
    assign m7_arlen   = 8'd0;
    assign m7_arsize  = 3'd0;
    assign m7_arburst = 2'b01;
    assign m7_arlock  = 1'b0;
    assign m7_arcache = 4'b0000;
    assign m7_arprot  = 3'b000;
    assign m7_arqos   = 4'b0000;
    assign m7_arvalid = 1'b0;
    
    // Read Data Channel
    assign m7_rready  = 1'b1;

    // Master 8 termination
    // Write Address Channel
    assign m8_awid    = {ID_WIDTH{1'b0}};
    assign m8_awaddr  = {ADDR_WIDTH{1'b0}};
    assign m8_awlen   = 8'd0;
    assign m8_awsize  = 3'd0;
    assign m8_awburst = 2'b01;
    assign m8_awlock  = 1'b0;
    assign m8_awcache = 4'b0000;
    assign m8_awprot  = 3'b000;
    assign m8_awqos   = 4'b0000;
    assign m8_awvalid = 1'b0;
    
    // Write Data Channel
    assign m8_wdata   = {DATA_WIDTH{1'b0}};
    assign m8_wstrb   = {(DATA_WIDTH/8){1'b0}};
    assign m8_wlast   = 1'b0;
    assign m8_wvalid  = 1'b0;
    
    // Write Response Channel
    assign m8_bready  = 1'b1;
    
    // Read Address Channel
    assign m8_arid    = {ID_WIDTH{1'b0}};
    assign m8_araddr  = {ADDR_WIDTH{1'b0}};
    assign m8_arlen   = 8'd0;
    assign m8_arsize  = 3'd0;
    assign m8_arburst = 2'b01;
    assign m8_arlock  = 1'b0;
    assign m8_arcache = 4'b0000;
    assign m8_arprot  = 3'b000;
    assign m8_arqos   = 4'b0000;
    assign m8_arvalid = 1'b0;
    
    // Read Data Channel
    assign m8_rready  = 1'b1;

    
    // Slave response logic for testing
    // Slave 0 (DDR0) - Simple memory model
    always @(posedge clk) begin
        if (!rst_n) begin
            s0_awready <= 1'b0;
            s0_wready  <= 1'b0;
            s0_bvalid  <= 1'b0;
            s0_arready <= 1'b0;
            s0_rvalid  <= 1'b0;
        end else begin
            // Simple handshaking
            s0_awready <= 1'b1;
            s0_wready  <= 1'b1;
            s0_arready <= 1'b1;
            
            // Write response
            if (s0_awvalid && s0_awready && s0_wvalid && s0_wready && s0_wlast) begin
                s0_bvalid <= 1'b1;
                s0_bid    <= s0_awid;
                s0_bresp  <= 2'b00; // OKAY
            end else if (s0_bready && s0_bvalid) begin
                s0_bvalid <= 1'b0;
            end
            
            // Read response (single beat for now)
            if (s0_arvalid && s0_arready) begin
                s0_rvalid <= 1'b1;
                s0_rid    <= s0_arid;
                s0_rdata  <= {DATA_WIDTH{1'b0}}; // Return zeros
                s0_rresp  <= 2'b00; // OKAY
                s0_rlast  <= 1'b1;  // Single beat
            end else if (s0_rready && s0_rvalid) begin
                s0_rvalid <= 1'b0;
            end
        end
    end

    // Slave 1 (DDR1) - Simple memory model
    always @(posedge clk) begin
        if (!rst_n) begin
            s1_awready <= 1'b0;
            s1_wready  <= 1'b0;
            s1_bvalid  <= 1'b0;
            s1_arready <= 1'b0;
            s1_rvalid  <= 1'b0;
        end else begin
            // Simple handshaking
            s1_awready <= 1'b1;
            s1_wready  <= 1'b1;
            s1_arready <= 1'b1;
            
            // Write response
            if (s1_awvalid && s1_awready && s1_wvalid && s1_wready && s1_wlast) begin
                s1_bvalid <= 1'b1;
                s1_bid    <= s1_awid;
                s1_bresp  <= 2'b00; // OKAY
            end else if (s1_bready && s1_bvalid) begin
                s1_bvalid <= 1'b0;
            end
            
            // Read response (single beat for now)
            if (s1_arvalid && s1_arready) begin
                s1_rvalid <= 1'b1;
                s1_rid    <= s1_arid;
                s1_rdata  <= {DATA_WIDTH{1'b0}}; // Return zeros
                s1_rresp  <= 2'b00; // OKAY
                s1_rlast  <= 1'b1;  // Single beat
            end else if (s1_rready && s1_rvalid) begin
                s1_rvalid <= 1'b0;
            end
        end
    end

    // Slave 2 (SRAM0) - Simple memory model
    always @(posedge clk) begin
        if (!rst_n) begin
            s2_awready <= 1'b0;
            s2_wready  <= 1'b0;
            s2_bvalid  <= 1'b0;
            s2_arready <= 1'b0;
            s2_rvalid  <= 1'b0;
        end else begin
            // Simple handshaking
            s2_awready <= 1'b1;
            s2_wready  <= 1'b1;
            s2_arready <= 1'b1;
            
            // Write response
            if (s2_awvalid && s2_awready && s2_wvalid && s2_wready && s2_wlast) begin
                s2_bvalid <= 1'b1;
                s2_bid    <= s2_awid;
                s2_bresp  <= 2'b00; // OKAY
            end else if (s2_bready && s2_bvalid) begin
                s2_bvalid <= 1'b0;
            end
            
            // Read response (single beat for now)
            if (s2_arvalid && s2_arready) begin
                s2_rvalid <= 1'b1;
                s2_rid    <= s2_arid;
                s2_rdata  <= {DATA_WIDTH{1'b0}}; // Return zeros
                s2_rresp  <= 2'b00; // OKAY
                s2_rlast  <= 1'b1;  // Single beat
            end else if (s2_rready && s2_rvalid) begin
                s2_rvalid <= 1'b0;
            end
        end
    end

    // Slave 3 (SRAM1) - Simple memory model
    always @(posedge clk) begin
        if (!rst_n) begin
            s3_awready <= 1'b0;
            s3_wready  <= 1'b0;
            s3_bvalid  <= 1'b0;
            s3_arready <= 1'b0;
            s3_rvalid  <= 1'b0;
        end else begin
            // Simple handshaking
            s3_awready <= 1'b1;
            s3_wready  <= 1'b1;
            s3_arready <= 1'b1;
            
            // Write response
            if (s3_awvalid && s3_awready && s3_wvalid && s3_wready && s3_wlast) begin
                s3_bvalid <= 1'b1;
                s3_bid    <= s3_awid;
                s3_bresp  <= 2'b00; // OKAY
            end else if (s3_bready && s3_bvalid) begin
                s3_bvalid <= 1'b0;
            end
            
            // Read response (single beat for now)
            if (s3_arvalid && s3_arready) begin
                s3_rvalid <= 1'b1;
                s3_rid    <= s3_arid;
                s3_rdata  <= {DATA_WIDTH{1'b0}}; // Return zeros
                s3_rresp  <= 2'b00; // OKAY
                s3_rlast  <= 1'b1;  // Single beat
            end else if (s3_rready && s3_rvalid) begin
                s3_rvalid <= 1'b0;
            end
        end
    end

    // Slave 4 (ROM) - Simple memory model
    always @(posedge clk) begin
        if (!rst_n) begin
            s4_awready <= 1'b0;
            s4_wready  <= 1'b0;
            s4_bvalid  <= 1'b0;
            s4_arready <= 1'b0;
            s4_rvalid  <= 1'b0;
        end else begin
            // Simple handshaking
            s4_awready <= 1'b1;
            s4_wready  <= 1'b1;
            s4_arready <= 1'b1;
            
            // Write response
            if (s4_awvalid && s4_awready && s4_wvalid && s4_wready && s4_wlast) begin
                s4_bvalid <= 1'b1;
                s4_bid    <= s4_awid;
                s4_bresp  <= 2'b00; // OKAY
            end else if (s4_bready && s4_bvalid) begin
                s4_bvalid <= 1'b0;
            end
            
            // Read response (single beat for now)
            if (s4_arvalid && s4_arready) begin
                s4_rvalid <= 1'b1;
                s4_rid    <= s4_arid;
                s4_rdata  <= {DATA_WIDTH{1'b0}}; // Return zeros
                s4_rresp  <= 2'b00; // OKAY
                s4_rlast  <= 1'b1;  // Single beat
            end else if (s4_rready && s4_rvalid) begin
                s4_rvalid <= 1'b0;
            end
        end
    end

    // Slave 5 (APB0) - Simple memory model
    always @(posedge clk) begin
        if (!rst_n) begin
            s5_awready <= 1'b0;
            s5_wready  <= 1'b0;
            s5_bvalid  <= 1'b0;
            s5_arready <= 1'b0;
            s5_rvalid  <= 1'b0;
        end else begin
            // Simple handshaking
            s5_awready <= 1'b1;
            s5_wready  <= 1'b1;
            s5_arready <= 1'b1;
            
            // Write response
            if (s5_awvalid && s5_awready && s5_wvalid && s5_wready && s5_wlast) begin
                s5_bvalid <= 1'b1;
                s5_bid    <= s5_awid;
                s5_bresp  <= 2'b00; // OKAY
            end else if (s5_bready && s5_bvalid) begin
                s5_bvalid <= 1'b0;
            end
            
            // Read response (single beat for now)
            if (s5_arvalid && s5_arready) begin
                s5_rvalid <= 1'b1;
                s5_rid    <= s5_arid;
                s5_rdata  <= {DATA_WIDTH{1'b0}}; // Return zeros
                s5_rresp  <= 2'b00; // OKAY
                s5_rlast  <= 1'b1;  // Single beat
            end else if (s5_rready && s5_rvalid) begin
                s5_rvalid <= 1'b0;
            end
        end
    end

    // Slave 6 (APB1) - Simple memory model
    always @(posedge clk) begin
        if (!rst_n) begin
            s6_awready <= 1'b0;
            s6_wready  <= 1'b0;
            s6_bvalid  <= 1'b0;
            s6_arready <= 1'b0;
            s6_rvalid  <= 1'b0;
        end else begin
            // Simple handshaking
            s6_awready <= 1'b1;
            s6_wready  <= 1'b1;
            s6_arready <= 1'b1;
            
            // Write response
            if (s6_awvalid && s6_awready && s6_wvalid && s6_wready && s6_wlast) begin
                s6_bvalid <= 1'b1;
                s6_bid    <= s6_awid;
                s6_bresp  <= 2'b00; // OKAY
            end else if (s6_bready && s6_bvalid) begin
                s6_bvalid <= 1'b0;
            end
            
            // Read response (single beat for now)
            if (s6_arvalid && s6_arready) begin
                s6_rvalid <= 1'b1;
                s6_rid    <= s6_arid;
                s6_rdata  <= {DATA_WIDTH{1'b0}}; // Return zeros
                s6_rresp  <= 2'b00; // OKAY
                s6_rlast  <= 1'b1;  // Single beat
            end else if (s6_rready && s6_rvalid) begin
                s6_rvalid <= 1'b0;
            end
        end
    end

    // Slave 7 (PCIe) - Simple memory model
    always @(posedge clk) begin
        if (!rst_n) begin
            s7_awready <= 1'b0;
            s7_wready  <= 1'b0;
            s7_bvalid  <= 1'b0;
            s7_arready <= 1'b0;
            s7_rvalid  <= 1'b0;
        end else begin
            // Simple handshaking
            s7_awready <= 1'b1;
            s7_wready  <= 1'b1;
            s7_arready <= 1'b1;
            
            // Write response
            if (s7_awvalid && s7_awready && s7_wvalid && s7_wready && s7_wlast) begin
                s7_bvalid <= 1'b1;
                s7_bid    <= s7_awid;
                s7_bresp  <= 2'b00; // OKAY
            end else if (s7_bready && s7_bvalid) begin
                s7_bvalid <= 1'b0;
            end
            
            // Read response (single beat for now)
            if (s7_arvalid && s7_arready) begin
                s7_rvalid <= 1'b1;
                s7_rid    <= s7_arid;
                s7_rdata  <= {DATA_WIDTH{1'b0}}; // Return zeros
                s7_rresp  <= 2'b00; // OKAY
                s7_rlast  <= 1'b1;  // Single beat
            end else if (s7_rready && s7_rvalid) begin
                s7_rvalid <= 1'b0;
            end
        end
    end

    // Slave 8 (CUSTOM) - Simple memory model
    always @(posedge clk) begin
        if (!rst_n) begin
            s8_awready <= 1'b0;
            s8_wready  <= 1'b0;
            s8_bvalid  <= 1'b0;
            s8_arready <= 1'b0;
            s8_rvalid  <= 1'b0;
        end else begin
            // Simple handshaking
            s8_awready <= 1'b1;
            s8_wready  <= 1'b1;
            s8_arready <= 1'b1;
            
            // Write response
            if (s8_awvalid && s8_awready && s8_wvalid && s8_wready && s8_wlast) begin
                s8_bvalid <= 1'b1;
                s8_bid    <= s8_awid;
                s8_bresp  <= 2'b00; // OKAY
            end else if (s8_bready && s8_bvalid) begin
                s8_bvalid <= 1'b0;
            end
            
            // Read response (single beat for now)
            if (s8_arvalid && s8_arready) begin
                s8_rvalid <= 1'b1;
                s8_rid    <= s8_arid;
                s8_rdata  <= {DATA_WIDTH{1'b0}}; // Return zeros
                s8_rresp  <= 2'b00; // OKAY
                s8_rlast  <= 1'b1;  // Single beat
            end else if (s8_rready && s8_rvalid) begin
                s8_rvalid <= 1'b0;
            end
        end
    end


endmodule : dut_wrapper
