//==============================================================================
// HVL Top Module
// Generated by AMBA Bus Matrix Configuration Tool
// Date: 2025-08-06 13:45:52
//==============================================================================

module hvl_top;
    
    import uvm_pkg::*;
    import axi4_test_pkg::*;
    
    initial begin
        // Run UVM test
        run_test();
    end
    
endmodule : hvl_top
