//==============================================================================
// AXI4 Virtual Sequencer
// Generated by AMBA Bus Matrix Configuration Tool
// Date: 2025-08-08 23:02:40
//==============================================================================

class axi4_virtual_sequencer extends uvm_sequencer;
    
    `uvm_component_utils(axi4_virtual_sequencer)
    
    // Master sequencers
    axi4_master_sequencer master_seqr[15];
    
    // Slave sequencers
    axi4_slave_sequencer slave_seqr[15];
    
    // Environment configuration handle (using uvm_object to avoid circular dependency)
    uvm_object env_cfg;
    
    // Constructor
    function new(string name = "axi4_virtual_sequencer", uvm_component parent = null);
        super.new(name, parent);
    endfunction
    
endclass : axi4_virtual_sequencer
