//--------------------------------------------------------
// AXI Pipeline Stage Generator with FIFO Buffers
// Generates proper pipelined AXI interconnect stages with FIFO buffering
// Supports backpressure and prevents data loss
//--------------------------------------------------------
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "gen_amba_axi.h"

// Generate AXI pipeline stage with FIFO buffers
int gen_axi_pipeline_stage(unsigned int widthAD, unsigned int widthDA, unsigned int widthID, 
                          unsigned int userWidth, unsigned int fifo_depth, 
                          const char *module_name, FILE *fo) {
    if (fo == NULL || module_name == NULL) return 1;
    
    fprintf(fo, "//--------------------------------------------------------\n");
    fprintf(fo, "// AXI Pipeline Stage with FIFO Buffers: %s\n", module_name);
    fprintf(fo, "// Provides pipelining with proper backpressure handling\n");
    fprintf(fo, "// FIFO Depth: %d entries per channel\n", fifo_depth);
    fprintf(fo, "// Generated by Enhanced AXI Generator\n");
    fprintf(fo, "//--------------------------------------------------------\n");
    fprintf(fo, "`timescale 1ns/1ps\n\n");
    
    fprintf(fo, "module %s #(\n", module_name);
    fprintf(fo, "    parameter ADDR_WIDTH  = %d,\n", widthAD);
    fprintf(fo, "    parameter DATA_WIDTH  = %d,\n", widthDA);
    fprintf(fo, "    parameter ID_WIDTH    = %d,\n", widthID);
    fprintf(fo, "    parameter USER_WIDTH  = %d,\n", userWidth);
    fprintf(fo, "    parameter STRB_WIDTH  = (DATA_WIDTH/8),\n");
    fprintf(fo, "    parameter FIFO_DEPTH  = %d\n", fifo_depth);
    fprintf(fo, ")(\n");
    fprintf(fo, "    input wire aclk,\n");
    fprintf(fo, "    input wire aresetn,\n\n");
    
    // Input AXI interface
    fprintf(fo, "    // Input AXI Interface\n");
    fprintf(fo, "    // Write Address Channel\n");
    fprintf(fo, "    input  wire [ID_WIDTH-1:0]     s_awid,\n");
    fprintf(fo, "    input  wire [ADDR_WIDTH-1:0]   s_awaddr,\n");
    fprintf(fo, "    input  wire [7:0]              s_awlen,\n");
    fprintf(fo, "    input  wire [2:0]              s_awsize,\n");
    fprintf(fo, "    input  wire [1:0]              s_awburst,\n");
    fprintf(fo, "    input  wire                    s_awlock,\n");
    fprintf(fo, "    input  wire [3:0]              s_awcache,\n");
    fprintf(fo, "    input  wire [2:0]              s_awprot,\n");
    fprintf(fo, "    input  wire [3:0]              s_awqos,\n");
    fprintf(fo, "    input  wire [3:0]              s_awregion,\n");
    fprintf(fo, "    input  wire [USER_WIDTH-1:0]   s_awuser,\n");
    fprintf(fo, "    input  wire                    s_awvalid,\n");
    fprintf(fo, "    output wire                    s_awready,\n\n");
    
    fprintf(fo, "    // Write Data Channel\n");
    fprintf(fo, "    input  wire [DATA_WIDTH-1:0]   s_wdata,\n");
    fprintf(fo, "    input  wire [STRB_WIDTH-1:0]   s_wstrb,\n");
    fprintf(fo, "    input  wire                    s_wlast,\n");
    fprintf(fo, "    input  wire [USER_WIDTH-1:0]   s_wuser,\n");
    fprintf(fo, "    input  wire                    s_wvalid,\n");
    fprintf(fo, "    output wire                    s_wready,\n\n");
    
    fprintf(fo, "    // Write Response Channel\n");
    fprintf(fo, "    output wire [ID_WIDTH-1:0]     s_bid,\n");
    fprintf(fo, "    output wire [1:0]              s_bresp,\n");
    fprintf(fo, "    output wire [USER_WIDTH-1:0]   s_buser,\n");
    fprintf(fo, "    output wire                    s_bvalid,\n");
    fprintf(fo, "    input  wire                    s_bready,\n\n");
    
    fprintf(fo, "    // Read Address Channel\n");
    fprintf(fo, "    input  wire [ID_WIDTH-1:0]     s_arid,\n");
    fprintf(fo, "    input  wire [ADDR_WIDTH-1:0]   s_araddr,\n");
    fprintf(fo, "    input  wire [7:0]              s_arlen,\n");
    fprintf(fo, "    input  wire [2:0]              s_arsize,\n");
    fprintf(fo, "    input  wire [1:0]              s_arburst,\n");
    fprintf(fo, "    input  wire                    s_arlock,\n");
    fprintf(fo, "    input  wire [3:0]              s_arcache,\n");
    fprintf(fo, "    input  wire [2:0]              s_arprot,\n");
    fprintf(fo, "    input  wire [3:0]              s_arqos,\n");
    fprintf(fo, "    input  wire [3:0]              s_arregion,\n");
    fprintf(fo, "    input  wire [USER_WIDTH-1:0]   s_aruser,\n");
    fprintf(fo, "    input  wire                    s_arvalid,\n");
    fprintf(fo, "    output wire                    s_arready,\n\n");
    
    fprintf(fo, "    // Read Data Channel\n");
    fprintf(fo, "    output wire [ID_WIDTH-1:0]     s_rid,\n");
    fprintf(fo, "    output wire [DATA_WIDTH-1:0]   s_rdata,\n");
    fprintf(fo, "    output wire [1:0]              s_rresp,\n");
    fprintf(fo, "    output wire                    s_rlast,\n");
    fprintf(fo, "    output wire [USER_WIDTH-1:0]   s_ruser,\n");
    fprintf(fo, "    output wire                    s_rvalid,\n");
    fprintf(fo, "    input  wire                    s_rready,\n\n");
    
    // Output AXI interface
    fprintf(fo, "    // Output AXI Interface\n");
    fprintf(fo, "    // Write Address Channel\n");
    fprintf(fo, "    output wire [ID_WIDTH-1:0]     m_awid,\n");
    fprintf(fo, "    output wire [ADDR_WIDTH-1:0]   m_awaddr,\n");
    fprintf(fo, "    output wire [7:0]              m_awlen,\n");
    fprintf(fo, "    output wire [2:0]              m_awsize,\n");
    fprintf(fo, "    output wire [1:0]              m_awburst,\n");
    fprintf(fo, "    output wire                    m_awlock,\n");
    fprintf(fo, "    output wire [3:0]              m_awcache,\n");
    fprintf(fo, "    output wire [2:0]              m_awprot,\n");
    fprintf(fo, "    output wire [3:0]              m_awqos,\n");
    fprintf(fo, "    output wire [3:0]              m_awregion,\n");
    fprintf(fo, "    output wire [USER_WIDTH-1:0]   m_awuser,\n");
    fprintf(fo, "    output wire                    m_awvalid,\n");
    fprintf(fo, "    input  wire                    m_awready,\n\n");
    
    fprintf(fo, "    // Write Data Channel\n");
    fprintf(fo, "    output wire [DATA_WIDTH-1:0]   m_wdata,\n");
    fprintf(fo, "    output wire [STRB_WIDTH-1:0]   m_wstrb,\n");
    fprintf(fo, "    output wire                    m_wlast,\n");
    fprintf(fo, "    output wire [USER_WIDTH-1:0]   m_wuser,\n");
    fprintf(fo, "    output wire                    m_wvalid,\n");
    fprintf(fo, "    input  wire                    m_wready,\n\n");
    
    fprintf(fo, "    // Write Response Channel\n");
    fprintf(fo, "    input  wire [ID_WIDTH-1:0]     m_bid,\n");
    fprintf(fo, "    input  wire [1:0]              m_bresp,\n");
    fprintf(fo, "    input  wire [USER_WIDTH-1:0]   m_buser,\n");
    fprintf(fo, "    input  wire                    m_bvalid,\n");
    fprintf(fo, "    output wire                    m_bready,\n\n");
    
    fprintf(fo, "    // Read Address Channel\n");
    fprintf(fo, "    output wire [ID_WIDTH-1:0]     m_arid,\n");
    fprintf(fo, "    output wire [ADDR_WIDTH-1:0]   m_araddr,\n");
    fprintf(fo, "    output wire [7:0]              m_arlen,\n");
    fprintf(fo, "    output wire [2:0]              m_arsize,\n");
    fprintf(fo, "    output wire [1:0]              m_arburst,\n");
    fprintf(fo, "    output wire                    m_arlock,\n");
    fprintf(fo, "    output wire [3:0]              m_arcache,\n");
    fprintf(fo, "    output wire [2:0]              m_arprot,\n");
    fprintf(fo, "    output wire [3:0]              m_arqos,\n");
    fprintf(fo, "    output wire [3:0]              m_arregion,\n");
    fprintf(fo, "    output wire [USER_WIDTH-1:0]   m_aruser,\n");
    fprintf(fo, "    output wire                    m_arvalid,\n");
    fprintf(fo, "    input  wire                    m_arready,\n\n");
    
    fprintf(fo, "    // Read Data Channel\n");
    fprintf(fo, "    input  wire [ID_WIDTH-1:0]     m_rid,\n");
    fprintf(fo, "    input  wire [DATA_WIDTH-1:0]   m_rdata,\n");
    fprintf(fo, "    input  wire [1:0]              m_rresp,\n");
    fprintf(fo, "    input  wire                    m_rlast,\n");
    fprintf(fo, "    input  wire [USER_WIDTH-1:0]   m_ruser,\n");
    fprintf(fo, "    input  wire                    m_rvalid,\n");
    fprintf(fo, "    output wire                    m_rready\n");
    fprintf(fo, ");\n\n");
    
    // FIFO instantiations for each channel
    fprintf(fo, "    // AW Channel FIFO\n");
    fprintf(fo, "    axi_channel_fifo_aw #(\n");
    fprintf(fo, "        .ADDR_WIDTH(ADDR_WIDTH),\n");
    fprintf(fo, "        .DATA_WIDTH(DATA_WIDTH),\n");
    fprintf(fo, "        .ID_WIDTH(ID_WIDTH),\n");
    fprintf(fo, "        .USER_WIDTH(USER_WIDTH),\n");
    fprintf(fo, "        .FIFO_DEPTH(FIFO_DEPTH)\n");
    fprintf(fo, "    ) aw_fifo (\n");
    fprintf(fo, "        .aclk(aclk),\n");
    fprintf(fo, "        .aresetn(aresetn),\n");
    fprintf(fo, "        .in_awid(s_awid), .in_awaddr(s_awaddr), .in_awlen(s_awlen),\n");
    fprintf(fo, "        .in_awsize(s_awsize), .in_awburst(s_awburst), .in_awlock(s_awlock),\n");
    fprintf(fo, "        .in_awcache(s_awcache), .in_awprot(s_awprot), .in_awqos(s_awqos),\n");
    fprintf(fo, "        .in_awregion(s_awregion), .in_awuser(s_awuser),\n");
    fprintf(fo, "        .in_awvalid(s_awvalid), .in_awready(s_awready),\n");
    fprintf(fo, "        .out_awid(m_awid), .out_awaddr(m_awaddr), .out_awlen(m_awlen),\n");
    fprintf(fo, "        .out_awsize(m_awsize), .out_awburst(m_awburst), .out_awlock(m_awlock),\n");
    fprintf(fo, "        .out_awcache(m_awcache), .out_awprot(m_awprot), .out_awqos(m_awqos),\n");
    fprintf(fo, "        .out_awregion(m_awregion), .out_awuser(m_awuser),\n");
    fprintf(fo, "        .out_awvalid(m_awvalid), .out_awready(m_awready)\n");
    fprintf(fo, "    );\n\n");
    
    fprintf(fo, "    // W Channel FIFO\n");
    fprintf(fo, "    axi_channel_fifo_w #(\n");
    fprintf(fo, "        .ADDR_WIDTH(ADDR_WIDTH),\n");
    fprintf(fo, "        .DATA_WIDTH(DATA_WIDTH),\n");
    fprintf(fo, "        .ID_WIDTH(ID_WIDTH),\n");
    fprintf(fo, "        .USER_WIDTH(USER_WIDTH),\n");
    fprintf(fo, "        .FIFO_DEPTH(FIFO_DEPTH)\n");
    fprintf(fo, "    ) w_fifo (\n");
    fprintf(fo, "        .aclk(aclk),\n");
    fprintf(fo, "        .aresetn(aresetn),\n");
    fprintf(fo, "        .in_wdata(s_wdata), .in_wstrb(s_wstrb),\n");
    fprintf(fo, "        .in_wlast(s_wlast), .in_wuser(s_wuser),\n");
    fprintf(fo, "        .in_wvalid(s_wvalid), .in_wready(s_wready),\n");
    fprintf(fo, "        .out_wdata(m_wdata), .out_wstrb(m_wstrb),\n");
    fprintf(fo, "        .out_wlast(m_wlast), .out_wuser(m_wuser),\n");
    fprintf(fo, "        .out_wvalid(m_wvalid), .out_wready(m_wready)\n");
    fprintf(fo, "    );\n\n");
    
    fprintf(fo, "    // AR Channel FIFO\n");
    fprintf(fo, "    axi_channel_fifo_ar #(\n");
    fprintf(fo, "        .ADDR_WIDTH(ADDR_WIDTH),\n");
    fprintf(fo, "        .DATA_WIDTH(DATA_WIDTH),\n");
    fprintf(fo, "        .ID_WIDTH(ID_WIDTH),\n");
    fprintf(fo, "        .USER_WIDTH(USER_WIDTH),\n");
    fprintf(fo, "        .FIFO_DEPTH(FIFO_DEPTH)\n");
    fprintf(fo, "    ) ar_fifo (\n");
    fprintf(fo, "        .aclk(aclk),\n");
    fprintf(fo, "        .aresetn(aresetn),\n");
    fprintf(fo, "        .in_arid(s_arid), .in_araddr(s_araddr), .in_arlen(s_arlen),\n");
    fprintf(fo, "        .in_arsize(s_arsize), .in_arburst(s_arburst), .in_arlock(s_arlock),\n");
    fprintf(fo, "        .in_arcache(s_arcache), .in_arprot(s_arprot), .in_arqos(s_arqos),\n");
    fprintf(fo, "        .in_arregion(s_arregion), .in_aruser(s_aruser),\n");
    fprintf(fo, "        .in_arvalid(s_arvalid), .in_arready(s_arready),\n");
    fprintf(fo, "        .out_arid(m_arid), .out_araddr(m_araddr), .out_arlen(m_arlen),\n");
    fprintf(fo, "        .out_arsize(m_arsize), .out_arburst(m_arburst), .out_arlock(m_arlock),\n");
    fprintf(fo, "        .out_arcache(m_arcache), .out_arprot(m_arprot), .out_arqos(m_arqos),\n");
    fprintf(fo, "        .out_arregion(m_arregion), .out_aruser(m_aruser),\n");
    fprintf(fo, "        .out_arvalid(m_arvalid), .out_arready(m_arready)\n");
    fprintf(fo, "    );\n\n");
    
    fprintf(fo, "    // B and R channels are response channels - typically pass through\n");
    fprintf(fo, "    // or have smaller FIFOs depending on design requirements\n");
    fprintf(fo, "    assign s_bid = m_bid;\n");
    fprintf(fo, "    assign s_bresp = m_bresp;\n");
    fprintf(fo, "    assign s_buser = m_buser;\n");
    fprintf(fo, "    assign s_bvalid = m_bvalid;\n");
    fprintf(fo, "    assign m_bready = s_bready;\n\n");
    
    fprintf(fo, "    assign s_rid = m_rid;\n");
    fprintf(fo, "    assign s_rdata = m_rdata;\n");
    fprintf(fo, "    assign s_rresp = m_rresp;\n");
    fprintf(fo, "    assign s_rlast = m_rlast;\n");
    fprintf(fo, "    assign s_ruser = m_ruser;\n");
    fprintf(fo, "    assign s_rvalid = m_rvalid;\n");
    fprintf(fo, "    assign m_rready = s_rready;\n\n");
    
    fprintf(fo, "endmodule\n");
    
    return 0;
}

// Legacy wrapper for old pipeline generator
int gen_axi_pipeline( char *module_name
                    , unsigned int widthAD
                    , unsigned int widthDA  
                    , axi_features_t *features
                    , FILE *fo)
{
    if (fo==NULL) return 1;
    if (features==NULL) return 1;
    
    // Use new FIFO-based pipeline stage
    unsigned int fifo_depth = 8;  // Default FIFO depth
    if (features->pipeline_stages > 1) {
        fifo_depth = features->pipeline_stages * 4;  // Scale FIFO depth with stages
    }
    
    return gen_axi_pipeline_stage(widthAD, widthDA, 4, 8, fifo_depth, module_name, fo);
}
