//--------------------------------------------------------
// Copyright (c) 2025 Enhanced AXI Generator  
// USER signal wrapper generation for AXI4 interfaces
//--------------------------------------------------------
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "gen_amba_axi.h"

int gen_axi_user_wrapper( char *module_name
                        , unsigned int widthAD
                        , unsigned int widthDA
                        , unsigned int widthID
                        , axi_features_t *features
                        , FILE *fo)
{
    if (fo==NULL) return 1;
    if (features==NULL) return 1;
    
    unsigned int user_width = features->width_user;
    if (user_width == 0) user_width = 1; // Default to 1 bit

    fprintf(fo, "//------------------------------------------------------------------------------\n");
    fprintf(fo, "// USER Signal Wrapper for %s\n", module_name);
    fprintf(fo, "// Generated by Enhanced RTL Generator (C)\n");
    fprintf(fo, "// Date: 2025-09-04\n");
    fprintf(fo, "//------------------------------------------------------------------------------\n");
    fprintf(fo, "\n");
    fprintf(fo, "module %s_user_wrapper #(\n", module_name);
    fprintf(fo, "    parameter USER_WIDTH = %d,\n", user_width);
    fprintf(fo, "    parameter ADDR_WIDTH = %d,\n", widthAD);
    fprintf(fo, "    parameter DATA_WIDTH = %d,\n", widthDA);
    fprintf(fo, "    parameter ID_WIDTH   = %d\n", widthID);
    fprintf(fo, ")(\n");
    fprintf(fo, "    input wire aclk,\n");
    fprintf(fo, "    input wire aresetn,\n");
    fprintf(fo, "    \n");
    fprintf(fo, "    // USER signals for each channel\n");
    fprintf(fo, "    input  wire [USER_WIDTH-1:0] awuser,\n");
    fprintf(fo, "    input  wire [USER_WIDTH-1:0] wuser,\n");
    fprintf(fo, "    output wire [USER_WIDTH-1:0] buser,\n");
    fprintf(fo, "    input  wire [USER_WIDTH-1:0] aruser,\n");
    fprintf(fo, "    output wire [USER_WIDTH-1:0] ruser,\n");
    fprintf(fo, "    \n");
    fprintf(fo, "    // Control signals\n");
    fprintf(fo, "    input  wire                  valid_in,\n");
    fprintf(fo, "    output wire                  ready_out\n");
    fprintf(fo, ");\n");
    fprintf(fo, "\n");
    
    // Generate synchronous USER signal processing with proper AXI4 compliance
    fprintf(fo, "// Synchronous USER signal processing with AXI4 compliance\n");
    fprintf(fo, "// Registers to hold USER signals during transaction processing\n");
    fprintf(fo, "reg [USER_WIDTH-1:0] awuser_reg;\n");
    fprintf(fo, "reg [USER_WIDTH-1:0] wuser_reg;\n"); 
    fprintf(fo, "reg [USER_WIDTH-1:0] buser_reg;\n");
    fprintf(fo, "reg [USER_WIDTH-1:0] aruser_reg;\n");
    fprintf(fo, "reg [USER_WIDTH-1:0] ruser_reg;\n");
    fprintf(fo, "reg ready_reg;\n");
    fprintf(fo, "\n");
    fprintf(fo, "// Synchronous processing of USER signals\n");
    fprintf(fo, "always @(posedge aclk or negedge aresetn) begin\n");
    fprintf(fo, "    if (!aresetn) begin\n");
    fprintf(fo, "        awuser_reg <= {USER_WIDTH{1'b0}};\n");
    fprintf(fo, "        wuser_reg  <= {USER_WIDTH{1'b0}};\n");
    fprintf(fo, "        buser_reg  <= {USER_WIDTH{1'b0}};\n");
    fprintf(fo, "        aruser_reg <= {USER_WIDTH{1'b0}};\n");
    fprintf(fo, "        ruser_reg  <= {USER_WIDTH{1'b0}};\n");
    fprintf(fo, "        ready_reg  <= 1'b0;\n");
    fprintf(fo, "    end else begin\n");
    fprintf(fo, "        // Process input USER signals with valid handshake\n");
    fprintf(fo, "        if (valid_in) begin\n");
    fprintf(fo, "            awuser_reg <= awuser;\n");
    fprintf(fo, "            wuser_reg  <= wuser;\n");
    fprintf(fo, "            aruser_reg <= aruser;\n");
    fprintf(fo, "            ready_reg  <= 1'b1;\n");
    fprintf(fo, "        end else begin\n");
    fprintf(fo, "            ready_reg  <= 1'b0;\n");
    fprintf(fo, "        end\n");
    fprintf(fo, "        \n");
    fprintf(fo, "        // Generate response USER signals based on request\n");
    fprintf(fo, "        // AXI4 spec: BUSER derived from AWUSER, RUSER from ARUSER\n");
    fprintf(fo, "        if (ready_reg) begin\n");
    fprintf(fo, "            buser_reg <= awuser_reg;  // Write response USER from write address USER\n");
    fprintf(fo, "            ruser_reg <= aruser_reg;  // Read response USER from read address USER\n");
    fprintf(fo, "        end\n");
    fprintf(fo, "    end\n");
    fprintf(fo, "end\n");
    fprintf(fo, "\n");
    fprintf(fo, "// Output assignments\n");
    fprintf(fo, "assign buser = buser_reg;\n");
    fprintf(fo, "assign ruser = ruser_reg;\n");
    fprintf(fo, "assign ready_out = ready_reg;\n");
    fprintf(fo, "\n");
    
    // Add optional USER signal validation logic
    fprintf(fo, "// Optional: USER signal validation and monitoring\n");
    fprintf(fo, "`ifdef AXI_USER_VALIDATION\n");
    fprintf(fo, "    // Validation logic for USER signals\n");
    fprintf(fo, "    always @(posedge aclk) begin\n");
    fprintf(fo, "        if (aresetn && valid_in) begin\n");
    fprintf(fo, "            // Check for reserved USER signal patterns\n");
    fprintf(fo, "            if (awuser == {USER_WIDTH{1'b1}}) begin\n");
    fprintf(fo, "                $display(\"Warning: AWUSER all-ones pattern detected at time %t\", $time);\n");
    fprintf(fo, "            end\n");
    fprintf(fo, "            if (aruser == {USER_WIDTH{1'b1}}) begin\n");
    fprintf(fo, "                $display(\"Warning: ARUSER all-ones pattern detected at time %t\", $time);\n");
    fprintf(fo, "            end\n");
    fprintf(fo, "        end\n");
    fprintf(fo, "    end\n");
    fprintf(fo, "`endif\n");
    fprintf(fo, "\n");
    
    fprintf(fo, "endmodule\n");
    fprintf(fo, "\n");
    
    return 0;
}