//--------------------------------------------------------
// AXI FIFO Buffer Generator
// Generates parametrizable FIFO buffers for AXI pipeline stages
// Supports proper backpressure and full/empty flags
//--------------------------------------------------------
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "gen_amba_axi.h"

// Generate a generic FIFO buffer module
int gen_axi_fifo_buffer(unsigned int data_width, unsigned int depth, 
                        const char *module_name, FILE *fo) {
    if (fo == NULL || module_name == NULL) return 1;
    
    // Calculate address width needed for depth
    unsigned int addr_width = (unsigned int)ceil(log2((double)depth));
    if (addr_width < 1) addr_width = 1;
    
    fprintf(fo, "//--------------------------------------------------------\n");
    fprintf(fo, "// AXI FIFO Buffer: %s\n", module_name);
    fprintf(fo, "// Synchronous FIFO with AXI-style handshaking\n");
    fprintf(fo, "// Data Width: %d bits, Depth: %d entries\n", data_width, depth);
    fprintf(fo, "// Generated by Enhanced AXI Generator\n");
    fprintf(fo, "//--------------------------------------------------------\n");
    fprintf(fo, "`timescale 1ns/1ps\n\n");
    
    fprintf(fo, "module %s #(\n", module_name);
    fprintf(fo, "    parameter DATA_WIDTH = %d,\n", data_width);
    fprintf(fo, "    parameter FIFO_DEPTH = %d,\n", depth);
    fprintf(fo, "    parameter ADDR_WIDTH = %d\n", addr_width);
    fprintf(fo, ")(\n");
    fprintf(fo, "    input  wire                    aclk,\n");
    fprintf(fo, "    input  wire                    aresetn,\n\n");
    
    // Write interface
    fprintf(fo, "    // Write Interface (Input)\n");
    fprintf(fo, "    input  wire [DATA_WIDTH-1:0]   wr_data,\n");
    fprintf(fo, "    input  wire                    wr_valid,\n");
    fprintf(fo, "    output wire                    wr_ready,\n\n");
    
    // Read interface
    fprintf(fo, "    // Read Interface (Output)\n");
    fprintf(fo, "    output wire [DATA_WIDTH-1:0]   rd_data,\n");
    fprintf(fo, "    output wire                    rd_valid,\n");
    fprintf(fo, "    input  wire                    rd_ready,\n\n");
    
    // Status signals
    fprintf(fo, "    // Status Signals\n");
    fprintf(fo, "    output wire                    fifo_full,\n");
    fprintf(fo, "    output wire                    fifo_empty,\n");
    fprintf(fo, "    output wire [ADDR_WIDTH:0]     fifo_count\n");
    fprintf(fo, ");\n\n");
    
    // Internal signals
    fprintf(fo, "    // Internal Signals\n");
    fprintf(fo, "    reg [DATA_WIDTH-1:0]   memory [0:FIFO_DEPTH-1];\n");
    fprintf(fo, "    reg [ADDR_WIDTH-1:0]   wr_ptr;\n");
    fprintf(fo, "    reg [ADDR_WIDTH-1:0]   rd_ptr;\n");
    fprintf(fo, "    reg [ADDR_WIDTH:0]     count;\n\n");
    
    fprintf(fo, "    wire wr_enable = wr_valid & wr_ready;\n");
    fprintf(fo, "    wire rd_enable = rd_valid & rd_ready;\n\n");
    
    // Status assignments
    fprintf(fo, "    // Status Logic\n");
    fprintf(fo, "    assign fifo_full  = (count == FIFO_DEPTH);\n");
    fprintf(fo, "    assign fifo_empty = (count == 0);\n");
    fprintf(fo, "    assign fifo_count = count;\n\n");
    
    fprintf(fo, "    // Ready/Valid Logic\n");
    fprintf(fo, "    assign wr_ready = !fifo_full;\n");
    fprintf(fo, "    assign rd_valid = !fifo_empty;\n\n");
    
    // Write logic
    fprintf(fo, "    // Write Logic\n");
    fprintf(fo, "    always @(posedge aclk or negedge aresetn) begin\n");
    fprintf(fo, "        if (!aresetn) begin\n");
    fprintf(fo, "            wr_ptr <= 0;\n");
    fprintf(fo, "        end else if (wr_enable) begin\n");
    fprintf(fo, "            memory[wr_ptr] <= wr_data;\n");
    fprintf(fo, "            if (wr_ptr == FIFO_DEPTH-1)\n");
    fprintf(fo, "                wr_ptr <= 0;\n");
    fprintf(fo, "            else\n");
    fprintf(fo, "                wr_ptr <= wr_ptr + 1;\n");
    fprintf(fo, "        end\n");
    fprintf(fo, "    end\n\n");
    
    // Read logic
    fprintf(fo, "    // Read Logic\n");
    fprintf(fo, "    always @(posedge aclk or negedge aresetn) begin\n");
    fprintf(fo, "        if (!aresetn) begin\n");
    fprintf(fo, "            rd_ptr <= 0;\n");
    fprintf(fo, "        end else if (rd_enable) begin\n");
    fprintf(fo, "            if (rd_ptr == FIFO_DEPTH-1)\n");
    fprintf(fo, "                rd_ptr <= 0;\n");
    fprintf(fo, "            else\n");
    fprintf(fo, "                rd_ptr <= rd_ptr + 1;\n");
    fprintf(fo, "        end\n");
    fprintf(fo, "    end\n\n");
    
    // Count logic
    fprintf(fo, "    // Count Logic\n");
    fprintf(fo, "    always @(posedge aclk or negedge aresetn) begin\n");
    fprintf(fo, "        if (!aresetn) begin\n");
    fprintf(fo, "            count <= 0;\n");
    fprintf(fo, "        end else begin\n");
    fprintf(fo, "            case ({wr_enable, rd_enable})\n");
    fprintf(fo, "                2'b01: count <= count - 1;  // Read only\n");
    fprintf(fo, "                2'b10: count <= count + 1;  // Write only\n");
    fprintf(fo, "                2'b11: count <= count;      // Read and Write\n");
    fprintf(fo, "                default: count <= count;    // No operation\n");
    fprintf(fo, "            endcase\n");
    fprintf(fo, "        end\n");
    fprintf(fo, "    end\n\n");
    
    // Output assignment
    fprintf(fo, "    // Output Data Assignment\n");
    fprintf(fo, "    assign rd_data = memory[rd_ptr];\n\n");
    
    fprintf(fo, "endmodule\n");
    
    return 0;
}

// Generate AXI channel-specific FIFO (with all AXI signals)
int gen_axi_channel_fifo(const char *channel_name, unsigned int addr_width, unsigned int data_width, 
                         unsigned int id_width, unsigned int user_width, unsigned int depth,
                         const char *module_name, FILE *fo) {
    if (fo == NULL || module_name == NULL || channel_name == NULL) return 1;
    
    unsigned int fifo_addr_width = (unsigned int)ceil(log2((double)depth));
    if (fifo_addr_width < 1) fifo_addr_width = 1;
    
    fprintf(fo, "//--------------------------------------------------------\n");
    fprintf(fo, "// AXI %s Channel FIFO: %s\n", channel_name, module_name);
    fprintf(fo, "// FIFO buffer for AXI %s channel with full protocol support\n", channel_name);
    fprintf(fo, "// Generated by Enhanced AXI Generator\n");
    fprintf(fo, "//--------------------------------------------------------\n");
    fprintf(fo, "`timescale 1ns/1ps\n\n");
    
    fprintf(fo, "module %s #(\n", module_name);
    fprintf(fo, "    parameter ADDR_WIDTH = %d,\n", addr_width);
    fprintf(fo, "    parameter DATA_WIDTH = %d,\n", data_width);
    fprintf(fo, "    parameter ID_WIDTH   = %d,\n", id_width);
    fprintf(fo, "    parameter USER_WIDTH = %d,\n", user_width);
    fprintf(fo, "    parameter FIFO_DEPTH = %d,\n", depth);
    fprintf(fo, "    parameter FIFO_ADDR_WIDTH = %d\n", fifo_addr_width);
    fprintf(fo, ")(\n");
    fprintf(fo, "    input wire aclk,\n");
    fprintf(fo, "    input wire aresetn,\n\n");
    
    // Generate channel-specific interfaces
    if (strcmp(channel_name, "AW") == 0 || strcmp(channel_name, "AR") == 0) {
        // Address channels
        fprintf(fo, "    // Input %s Channel\n", channel_name);
        fprintf(fo, "    input  wire [ID_WIDTH-1:0]     in_%sid,\n", (channel_name[1] == 'W') ? "aw" : "ar");
        fprintf(fo, "    input  wire [ADDR_WIDTH-1:0]   in_%saddr,\n", (channel_name[1] == 'W') ? "aw" : "ar");
        fprintf(fo, "    input  wire [7:0]              in_%slen,\n", (channel_name[1] == 'W') ? "aw" : "ar");
        fprintf(fo, "    input  wire [2:0]              in_%ssize,\n", (channel_name[1] == 'W') ? "aw" : "ar");
        fprintf(fo, "    input  wire [1:0]              in_%sburst,\n", (channel_name[1] == 'W') ? "aw" : "ar");
        fprintf(fo, "    input  wire                    in_%slock,\n", (channel_name[1] == 'W') ? "aw" : "ar");
        fprintf(fo, "    input  wire [3:0]              in_%scache,\n", (channel_name[1] == 'W') ? "aw" : "ar");
        fprintf(fo, "    input  wire [2:0]              in_%sprot,\n", (channel_name[1] == 'W') ? "aw" : "ar");
        fprintf(fo, "    input  wire [3:0]              in_%sqos,\n", (channel_name[1] == 'W') ? "aw" : "ar");
        fprintf(fo, "    input  wire [3:0]              in_%sregion,\n", (channel_name[1] == 'W') ? "aw" : "ar");
        fprintf(fo, "    input  wire [USER_WIDTH-1:0]   in_%suser,\n", (channel_name[1] == 'W') ? "aw" : "ar");
        fprintf(fo, "    input  wire                    in_%svalid,\n", (channel_name[1] == 'W') ? "aw" : "ar");
        fprintf(fo, "    output wire                    in_%sready,\n\n", (channel_name[1] == 'W') ? "aw" : "ar");
        
        fprintf(fo, "    // Output %s Channel\n", channel_name);
        fprintf(fo, "    output wire [ID_WIDTH-1:0]     out_%sid,\n", (channel_name[1] == 'W') ? "aw" : "ar");
        fprintf(fo, "    output wire [ADDR_WIDTH-1:0]   out_%saddr,\n", (channel_name[1] == 'W') ? "aw" : "ar");
        fprintf(fo, "    output wire [7:0]              out_%slen,\n", (channel_name[1] == 'W') ? "aw" : "ar");
        fprintf(fo, "    output wire [2:0]              out_%ssize,\n", (channel_name[1] == 'W') ? "aw" : "ar");
        fprintf(fo, "    output wire [1:0]              out_%sburst,\n", (channel_name[1] == 'W') ? "aw" : "ar");
        fprintf(fo, "    output wire                    out_%slock,\n", (channel_name[1] == 'W') ? "aw" : "ar");
        fprintf(fo, "    output wire [3:0]              out_%scache,\n", (channel_name[1] == 'W') ? "aw" : "ar");
        fprintf(fo, "    output wire [2:0]              out_%sprot,\n", (channel_name[1] == 'W') ? "aw" : "ar");
        fprintf(fo, "    output wire [3:0]              out_%sqos,\n", (channel_name[1] == 'W') ? "aw" : "ar");
        fprintf(fo, "    output wire [3:0]              out_%sregion,\n", (channel_name[1] == 'W') ? "aw" : "ar");
        fprintf(fo, "    output wire [USER_WIDTH-1:0]   out_%suser,\n", (channel_name[1] == 'W') ? "aw" : "ar");
        fprintf(fo, "    output wire                    out_%svalid,\n", (channel_name[1] == 'W') ? "aw" : "ar");
        fprintf(fo, "    input  wire                    out_%sready\n", (channel_name[1] == 'W') ? "aw" : "ar");
        
        // Pack/unpack data
        unsigned int pack_width = id_width + addr_width + 8 + 3 + 2 + 1 + 4 + 3 + 4 + 4 + user_width;
        fprintf(fo, ");\n\n");
        fprintf(fo, "    // Data packing width: %d bits\n", pack_width);
        fprintf(fo, "    localparam PACK_WIDTH = %d;\n", pack_width);
        fprintf(fo, "    wire [PACK_WIDTH-1:0] fifo_wr_data, fifo_rd_data;\n\n");
        
        const char *prefix = (channel_name[1] == 'W') ? "aw" : "ar";
        fprintf(fo, "    // Pack input data\n");
        fprintf(fo, "    assign fifo_wr_data = {in_%sid, in_%saddr, in_%slen, in_%ssize, in_%sburst,\n", 
                prefix, prefix, prefix, prefix, prefix);
        fprintf(fo, "                           in_%slock, in_%scache, in_%sprot, in_%sqos, \n",
                prefix, prefix, prefix, prefix);
        fprintf(fo, "                           in_%sregion, in_%suser};\n\n", prefix, prefix);
        
        fprintf(fo, "    // Unpack output data\n");
        fprintf(fo, "    assign {out_%sid, out_%saddr, out_%slen, out_%ssize, out_%sburst,\n",
                prefix, prefix, prefix, prefix, prefix);
        fprintf(fo, "            out_%slock, out_%scache, out_%sprot, out_%sqos,\n",
                prefix, prefix, prefix, prefix);
        fprintf(fo, "            out_%sregion, out_%suser} = fifo_rd_data;\n\n", prefix, prefix);
        
    } else if (strcmp(channel_name, "W") == 0) {
        // Write data channel
        fprintf(fo, "    // Input W Channel\n");
        fprintf(fo, "    input  wire [DATA_WIDTH-1:0]   in_wdata,\n");
        fprintf(fo, "    input  wire [DATA_WIDTH/8-1:0] in_wstrb,\n");
        fprintf(fo, "    input  wire                    in_wlast,\n");
        fprintf(fo, "    input  wire [USER_WIDTH-1:0]   in_wuser,\n");
        fprintf(fo, "    input  wire                    in_wvalid,\n");
        fprintf(fo, "    output wire                    in_wready,\n\n");
        
        fprintf(fo, "    // Output W Channel\n");
        fprintf(fo, "    output wire [DATA_WIDTH-1:0]   out_wdata,\n");
        fprintf(fo, "    output wire [DATA_WIDTH/8-1:0] out_wstrb,\n");
        fprintf(fo, "    output wire                    out_wlast,\n");
        fprintf(fo, "    output wire [USER_WIDTH-1:0]   out_wuser,\n");
        fprintf(fo, "    output wire                    out_wvalid,\n");
        fprintf(fo, "    input  wire                    out_wready\n");
        
        unsigned int pack_width = data_width + data_width/8 + 1 + user_width;
        fprintf(fo, ");\n\n");
        fprintf(fo, "    // Data packing width: %d bits\n", pack_width);
        fprintf(fo, "    localparam PACK_WIDTH = %d;\n", pack_width);
        fprintf(fo, "    wire [PACK_WIDTH-1:0] fifo_wr_data, fifo_rd_data;\n\n");
        
        fprintf(fo, "    // Pack input data\n");
        fprintf(fo, "    assign fifo_wr_data = {in_wdata, in_wstrb, in_wlast, in_wuser};\n\n");
        
        fprintf(fo, "    // Unpack output data\n");
        fprintf(fo, "    assign {out_wdata, out_wstrb, out_wlast, out_wuser} = fifo_rd_data;\n\n");
    }
    
    // Instantiate generic FIFO
    fprintf(fo, "    // Generic FIFO Instance\n");
    fprintf(fo, "    axi_fifo_buffer #(\n");
    fprintf(fo, "        .DATA_WIDTH(PACK_WIDTH),\n");
    fprintf(fo, "        .FIFO_DEPTH(FIFO_DEPTH),\n");
    fprintf(fo, "        .ADDR_WIDTH(FIFO_ADDR_WIDTH)\n");
    fprintf(fo, "    ) fifo_inst (\n");
    fprintf(fo, "        .aclk(aclk),\n");
    fprintf(fo, "        .aresetn(aresetn),\n");
    fprintf(fo, "        .wr_data(fifo_wr_data),\n");
    if (strcmp(channel_name, "AW") == 0 || strcmp(channel_name, "AR") == 0) {
        const char *prefix = (channel_name[1] == 'W') ? "aw" : "ar";
        fprintf(fo, "        .wr_valid(in_%svalid),\n", prefix);
        fprintf(fo, "        .wr_ready(in_%sready),\n", prefix);
        fprintf(fo, "        .rd_valid(out_%svalid),\n", prefix);
        fprintf(fo, "        .rd_ready(out_%sready),\n", prefix);
    } else {
        fprintf(fo, "        .wr_valid(in_wvalid),\n");
        fprintf(fo, "        .wr_ready(in_wready),\n");
        fprintf(fo, "        .rd_valid(out_wvalid),\n");
        fprintf(fo, "        .rd_ready(out_wready),\n");
    }
    fprintf(fo, "        .rd_data(fifo_rd_data),\n");
    fprintf(fo, "        .fifo_full(),\n");
    fprintf(fo, "        .fifo_empty(),\n");
    fprintf(fo, "        .fifo_count()\n");
    fprintf(fo, "    );\n\n");
    
    fprintf(fo, "endmodule\n");
    
    return 0;
}