//--------------------------------------------------------
// Copyright (c) 2016-2021 by Ando Ki (andoki@gmail.com)
// The contents and codes along with it are prepared
// in the hope that it will be useful to understand 
// Ando Ki's work, but WITHOUT ANY WARRANTY.
// The design is not guaranteed to work on all systems.
// While there are no known issues with using the design,
// no technical support will be provided for problems
// that might arise.
//--------------------------------------------------------
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <signal.h>
#include <assert.h>
#ifdef WIN32
#	include <windows.h>
#	include <io.h>
#endif
#include "gen_amba_axi.h"
#include "gen_axi_validation.h"

int main(int argc, char *argv[]) {
  extern void sig_handle(int);
  extern int  arg_parser(int, char **);
  extern const char program[];
  extern const unsigned int version;
  extern const char license[];
  extern int axi4;
  extern unsigned int numM, numS, widthAD, widthDA;
  extern char module[];
  extern char prefix[];
  extern char file[];
  extern FILE* fo;
  extern axi_features_t features;

  if ((signal(SIGINT, sig_handle)==SIG_ERR)
#ifndef WIN32
	  ||(signal(SIGQUIT, sig_handle)==SIG_ERR)
#endif
	  ) {
        fprintf(stderr, "Error: signal error\n");
        exit(1);
  }

  if (arg_parser(argc, argv)) return 1;

  // Enhanced validation framework
  validation_info("MAIN", "Starting enhanced validation framework");
  
  // Validate configuration matrix
  if (validate_configuration_matrix(numM, numS, widthAD, widthDA, &features)) {
    validation_error("MAIN", NULL, 0, "Configuration validation failed");
    return 1;
  }
  
  // Validate feature dependencies
  if (validate_feature_dependencies(&features)) {
    validation_error("MAIN", NULL, 0, "Feature dependency validation failed");
    return 1;
  }
  
  // ACE-Lite specific validation
  if (check_ace_lite_constraints(numM, numS, &features)) {
    validation_error("MAIN", NULL, 0, "ACE-Lite constraint validation failed");
    return 1;
  }

fprintf(fo, "//---------------------------------------------------------------------------\n");
fprintf(fo, "// gen_amba_axi.v generated by \"%s (%X)\"\n", program, version);
fprintf(fo, "// Enhanced with QoS, REGION, USER, Firewall, and CDC support\n");
fprintf(fo, "//---------------------------------------------------------------------------\n");
fprintf(fo, "`timescale 1ns/1ps\n");

  // Add ACE-Lite defines if enabled
  if (features.enable_ace_lite) {
    fprintf(fo, "\n// ACE-Lite feature defines - required for all modules\n");
    fprintf(fo, "`define AMBA_ACE_LITE\n");
    fprintf(fo, "`define AMBA_AXI_CACHE\n");
    fprintf(fo, "`define AMBA_AXI_PROT\n");
    fprintf(fo, "`define AMBA_QOS\n");
    fprintf(fo, "`define AMBA_AXI_AWUSER\n");
    fprintf(fo, "`define AMBA_AXI_WUSER\n");
    fprintf(fo, "`define AMBA_AXI_BUSER\n");
    fprintf(fo, "`define AMBA_AXI_ARUSER\n");
    fprintf(fo, "`define AMBA_AXI_RUSER\n\n");
  }

  if (gen_axi_amba( numM, numS, widthAD, widthDA, module, prefix, axi4, &features, fo )) return 1;

  // RTL validation is now generated inside modules by gen_axi_amba()

  // Pipeline and user wrapper features are now integrated within the main interconnect
  // No separate module generation needed - all features are embedded in gen_axi_amba()
  
  // Post-generation validation
  validation_info("MAIN", "Running post-generation validation");
  FILE* validation_log = fopen("validation.log", "w");
  int signal_errors = validate_signal_consistency(validation_log);
  if (signal_errors > 0) {
    validation_error("MAIN", NULL, 0, "Found %d signal consistency errors - check validation.log", signal_errors);
  }
  if (validation_log) fclose(validation_log);

fprintf(fo, "/* %s\n*/\n", license);

  return(0);
}
//--------------------------------------------------------
void sig_handle(int sig) {
  extern void cleanup();
  switch (sig) {
  case SIGINT:
#ifndef WIN32
  case SIGQUIT:
#endif
       exit(0);
       break;
  }
}
//--------------------------------------------------------
// Revision history
//
// 2018.07.19: Minor modification by Ando Ki.
// 2016.03.26: Startd by Ando Ki.
//--------------------------------------------------------
