//==============================================================================
// AXI4 Master Agent BFM
// Generated by AMBA Bus Matrix Configuration Tool
// Date: 2025-08-06 17:16:34
//==============================================================================

module axi4_master_agent_bfm #(
    parameter ADDR_WIDTH = 48,
    parameter DATA_WIDTH = 256,
    parameter ID_WIDTH   = 4
)(
    input aclk,
    input aresetn,
    axi4_if.master axi_intf  // Connect to AXI interface
);

    import axi4_globals_pkg::*;
    
    // Master driver BFM instance with interface connection
    axi4_master_driver_bfm #(
        .ADDR_WIDTH(ADDR_WIDTH),
        .DATA_WIDTH(DATA_WIDTH),
        .ID_WIDTH(ID_WIDTH)
    ) master_driver_bfm_h(
        .aclk(aclk), 
        .aresetn(aresetn),
        .axi_intf(axi_intf)
    );
    
    // Master monitor BFM instance
    axi4_master_monitor_bfm master_monitor_bfm_h(aclk, aresetn);

endmodule : axi4_master_agent_bfm
