//==============================================================================
// AXI4 Virtual Sequencer Package
// Generated by AMBA Bus Matrix Configuration Tool
// Date: 2025-07-29 20:00:21
//==============================================================================

package axi4_virtual_seqr_pkg;
    
    import uvm_pkg::*;
    `include "uvm_macros.svh"
    
    import axi4_master_pkg::*;
    import axi4_slave_pkg::*;
    
    `include "axi4_virtual_sequencer.sv"
    
endpackage : axi4_virtual_seqr_pkg
