//==============================================================================
// AXI4 Master Burst Sequence
// Generated by AMBA Bus Matrix Configuration Tool
// Date: 2025-08-04 09:43:29
//==============================================================================

class axi4_master_burst_seq extends axi4_master_base_seq;
    
    `uvm_object_utils(axi4_master_burst_seq)
    
    // Burst parameters
    rand axi4_burst_type_e burst_type;
    rand int burst_length;
    
    constraint burst_length_c {
        burst_length inside {1, 2, 4, 8, 16, 32, 64, 128, 256};
    }
    
    // Constructor
    function new(string name = "axi4_master_burst_seq");
        super.new(name);
    endfunction
    
    // Body method
    virtual task body();
        axi4_master_tx tx;
        
        `uvm_do_with(tx, {
            tx.tx_type == axi4_master_tx::WRITE;
            tx.awburst == burst_type;
            tx.awlen == burst_length - 1;
            tx.awsize == axi4_globals_pkg::SIZE_4B;
        })
    endtask : body
    
endclass : axi4_master_burst_seq
