//==============================================================================
// AXI4 Master Sequence Package
// Generated by AMBA Bus Matrix Configuration Tool
// Date: 2025-08-04 09:43:29
//==============================================================================

package axi4_master_seq_pkg;
    
    import uvm_pkg::*;
    `include "uvm_macros.svh"
    
    import axi4_globals_pkg::*;
    import axi4_master_pkg::*;
    
    // Include sequence files
    `include "axi4_master_base_seq.sv"
    `include "axi4_master_write_seq.sv"
    `include "axi4_master_read_seq.sv"
    `include "axi4_master_burst_seq.sv"
    `include "axi4_master_random_seq.sv"
    `include "axi4_master_qos_seq.sv"
    
endpackage : axi4_master_seq_pkg
