#!/bin/bash
# Demo script showing how to control UVM verbosity for enhanced logging

echo "======================================"
echo "AXI4 VIP Enhanced Logging Demo"
echo "======================================"
echo ""
echo "The VIP now includes comprehensive UVM_INFO logging at three levels:"
echo "  - UVM_LOW    : Key phase transitions and major events"
echo "  - UVM_MEDIUM : Transaction details and important operations"  
echo "  - UVM_HIGH   : Detailed debug information and periodic status"
echo ""
echo "To control verbosity, use the +UVM_VERBOSITY flag:"
echo ""
echo "1. Show only LOW messages (minimal):"
echo "   ./simv +UVM_TESTNAME=demo_logging_test +UVM_VERBOSITY=UVM_LOW"
echo ""
echo "2. Show LOW and MEDIUM messages (recommended for debug):"
echo "   ./simv +UVM_TESTNAME=demo_logging_test +UVM_VERBOSITY=UVM_MEDIUM"
echo ""
echo "3. Show all messages including HIGH (maximum detail):"
echo "   ./simv +UVM_TESTNAME=demo_logging_test +UVM_VERBOSITY=UVM_HIGH"
echo ""
echo "You can also filter by component:"
echo "   ./simv +uvm_set_verbosity=*master_driver*,UVM_HIGH,UVM_HIGH"
echo ""
echo "To correlate with waveforms:"
echo "1. Note the timestamp in UVM_INFO messages"
echo "2. Navigate to that time in your waveform viewer"
echo "3. The enhanced logging helps identify what the VIP is doing"
echo ""
echo "Example enhanced log output:"
echo "-------------------------------------"
echo "UVM_INFO @ 0: reporter [axi4_master_agent] Building master agent components"
echo "UVM_INFO @ 0: reporter [axi4_master_agent] Master agent mode: ACTIVE"
echo "UVM_INFO @ 100: reporter [axi4_master_driver] Starting master driver run_phase"
echo "UVM_INFO @ 200: reporter [axi4_master_driver] Waiting for next transaction"
echo "UVM_INFO @ 300: reporter [axi4_master_driver] Got WRITE transaction - addr=0x1000"
echo "UVM_INFO @ 300: reporter [axi4_master_driver] Transaction details - id=2, qos=0"
echo "UVM_INFO @ 400: reporter [axi4_master_monitor] Monitor active - checking"
echo "-------------------------------------"
