//==============================================================================
// AXI4 Master Base Sequence
// Generated by AMBA Bus Matrix Configuration Tool
// Date: 2025-07-29 14:34:40
//==============================================================================

class axi4_master_base_seq extends uvm_sequence #(axi4_master_tx);
    
    `uvm_object_utils(axi4_master_base_seq)
    
    // Number of transactions
    int num_trans = 1;
    
    // Constructor
    function new(string name = "axi4_master_base_seq");
        super.new(name);
    endfunction
    
    // Pre body
    virtual task pre_body();
        `uvm_info(get_type_name(), $sformatf("Pre-body: Starting sequence %s", get_type_name()), UVM_HIGH)
        // Objection handling if needed
    endtask
    
    // Post body  
    virtual task post_body();
        `uvm_info(get_type_name(), $sformatf("Post-body: Completed sequence %s", get_type_name()), UVM_HIGH)
        // Objection handling if needed
    endtask
    
    // Body method
    virtual task body();
        `uvm_info(get_type_name(), $sformatf("Starting %s with %0d transactions", get_type_name(), num_trans), UVM_MEDIUM)
        `uvm_info(get_type_name(), $sformatf("Sequence running on sequencer: %s", get_sequencer().get_full_name()), UVM_HIGH)
    endtask : body
    
endclass : axi4_master_base_seq
