//==============================================================================
// Axi4 Random Test
// Generated by AMBA Bus Matrix Configuration Tool  
// Date: 2025-08-06 17:07:31
//==============================================================================

class axi4_random_test extends axi4_base_test;
    
    `uvm_component_utils(axi4_random_test)
    
    // Constructor
    function new(string name = "axi4_random_test", uvm_component parent = null);
        super.new(name, parent);
    endfunction
    
    // Run phase
    virtual task run_phase(uvm_phase phase);
        axi4_random_virtual_seq vseq;
        
        phase.raise_objection(this);
        
        // Create and start virtual sequence
        vseq = axi4_random_virtual_seq::type_id::create("vseq");
        vseq.start(env.virtual_seqr);
        
        phase.drop_objection(this);
    endtask
    
endclass : axi4_random_test
