//==============================================================================
// HVL Top Module
// Generated by AMBA Bus Matrix Configuration Tool
// Date: 2025-08-09 12:32:51
//==============================================================================

module hvl_top;
    
    import uvm_pkg::*;
    import axi4_test_pkg::*;
    
    initial begin
        `ifdef DUMP_FSDB
            // FSDB dumping using system tasks
            $fsdbDumpfile("waves/axi4_vip.fsdb");
            $fsdbDumpvars(0, hdl_top, "+all");
            $fsdbDumpvars(0, hvl_top, "+all");
            $display("[%0t] FSDB dumping enabled to waves/axi4_vip.fsdb", $time);
        `endif
        
        `ifdef DUMP_VCD
            // VCD dumping
            $dumpfile("waves/axi4_vip.vcd");
            $dumpvars(0, hdl_top);
            $dumpvars(0, hvl_top);
            $display("[%0t] VCD dumping enabled to waves/axi4_vip.vcd", $time);
        `endif
        
        // Run UVM test
        run_test();
    end
    
endmodule : hvl_top
