//==============================================================================
// AXI4 Master Agent BFM
// Generated by AMBA Bus Matrix Configuration Tool
// Date: 2025-08-04 09:43:29
//==============================================================================

interface axi4_master_agent_bfm #(
    parameter ADDR_WIDTH = 32,
    parameter DATA_WIDTH = 32,
    parameter ID_WIDTH   = 4
)(
    input aclk,
    input aresetn
);

    import axi4_globals_pkg::*;
    
    // Master driver BFM instance (interface instantiation)
    axi4_master_driver_bfm master_driver_bfm_h(aclk, aresetn);
    
    // Master monitor BFM instance (interface instantiation)
    axi4_master_monitor_bfm master_monitor_bfm_h(aclk, aresetn);

endinterface : axi4_master_agent_bfm
